//----------------------------------------------------------------------------//
// Generated by LegUp High-Level Synthesis Tool Version 4.0 (http://legup.org)
// Compiled: Sun Jul 26 12:56:54 2015
// University of Toronto
// For research and academic purposes only. Commercial use is prohibited.
// Please send bugs to: legup@eecg.toronto.edu
// Date: Sat Apr 20 05:40:19 2019
//----------------------------------------------------------------------------//

`define MEMORY_CONTROLLER_ADDR_SIZE 32
`define MEMORY_CONTROLLER_DATA_SIZE 64
// Number of RAM elements: 3
`define MEMORY_CONTROLLER_TAG_SIZE 9

// Turn off warning 'ignoring unsupported system task'
// altera message_off 10175

`timescale 1 ns / 1 ns
module top
	(
		clk,
		reset,
		start,
		finish,
		waitrequest,
		return_val
	);
input clk;
input reset;
input start;
output wire finish;
input waitrequest;
output wire [31:0] return_val;
/* synthesis translate_off */
assign memory_controller_waitrequest = waitrequest;
/* synthesis translate_on */

main main_inst(
	.clk( clk ),
	.clk2x( clk2x ),
	.clk1x_follower( clk1x_follower ),
	.reset( reset ),
	.start( start ),
	.finish( finish ),
	.return_val( return_val ),
	.memory_controller_waitrequest(memory_controller_waitrequest)
);

endmodule

`timescale 1 ns / 1 ns
module main
(
	clk,
	clk2x,
	clk1x_follower,
	reset,
	start,
	finish,
	memory_controller_waitrequest,
	return_val
);

parameter [4:0] LEGUP_0 = 5'd0;
parameter [4:0] LEGUP_F_main_BB__0_1 = 5'd1;
parameter [4:0] LEGUP_F_main_BB_preheaderi_2 = 5'd2;
parameter [4:0] LEGUP_F_main_BB_preheaderi_3 = 5'd3;
parameter [4:0] LEGUP_F_main_BB_preheaderi_4 = 5'd4;
parameter [4:0] LEGUP_F_main_BB_preheaderi_5 = 5'd5;
parameter [4:0] LEGUP_F_main_BB_preheaderi_6 = 5'd6;
parameter [4:0] LEGUP_F_main_BB_preheaderi_7 = 5'd7;
parameter [4:0] LEGUP_F_main_BB_preheaderi_8 = 5'd8;
parameter [4:0] LEGUP_F_main_BB_preheaderi_9 = 5'd9;
parameter [4:0] LEGUP_F_main_BB_preheaderi_10 = 5'd10;
parameter [4:0] LEGUP_F_main_BB_preheaderi_11 = 5'd11;
parameter [4:0] LEGUP_F_main_BB_preheaderi_12 = 5'd12;
parameter [4:0] LEGUP_F_main_BB_preheaderi_13 = 5'd13;
parameter [4:0] LEGUP_F_main_BB_preheaderi_14 = 5'd14;
parameter [4:0] LEGUP_F_main_BB_preheaderi_15 = 5'd15;
parameter [4:0] LEGUP_F_main_BB_preheaderi_16 = 5'd16;
parameter [4:0] LEGUP_F_main_BB_preheaderi_17 = 5'd17;
parameter [4:0] LEGUP_F_main_BB_preheaderpreheader_18 = 5'd18;
parameter [4:0] LEGUP_F_main_BB_preheaderpreheader_crit_edgei_19 = 5'd19;
parameter [4:0] LEGUP_F_main_BB_preheader_20 = 5'd20;
parameter [4:0] LEGUP_loop_pipeline_wait_loop1_1_21 = 5'd21;
parameter [4:0] LEGUP_F_main_BB__64_22 = 5'd22;
parameter [4:0] LEGUP_F_main_BB__64_23 = 5'd23;
parameter [4:0] LEGUP_F_main_BB__65_24 = 5'd24;
parameter [4:0] LEGUP_F_main_BB__67_25 = 5'd25;
parameter [4:0] LEGUP_F_main_BB__69_26 = 5'd26;
parameter [4:0] LEGUP_F_main_BB__71_27 = 5'd27;
parameter [8:0] tag_offset = 9'd0;
parameter [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] tag_addr_offset = {tag_offset, 23'd0};

input  clk;
input  clk2x;
input  clk1x_follower;
input  reset;
input  start;
output reg  finish;
input  memory_controller_waitrequest;
output reg [31:0] return_val;
reg [4:0] cur_state;
reg [4:0] next_state;
reg [31:0] main_preheaderi_indvar7;
reg [31:0] main_preheaderi_indvar7_reg;
reg [31:0] main_preheaderi_y08i;
reg [31:0] main_preheaderi_y08i_reg;
reg [31:0] main_preheaderi_x07i;
reg [31:0] main_preheaderi_x07i_reg;
reg  main_preheaderi_1;
reg  main_preheaderi_1_reg;
reg [31:0] main_preheaderi_2;
reg [31:0] main_preheaderi_2_reg;
reg [31:0] main_preheaderi_3;
reg [31:0] main_preheaderi_3_reg;
reg [31:0] main_preheaderi_4;
reg [31:0] main_preheaderi_4_reg;
reg [31:0] main_preheaderi_i;
reg [31:0] main_preheaderi_i_reg;
reg [31:0] main_preheaderi_5;
reg [31:0] main_preheaderi_5_reg;
reg [31:0] main_preheaderi_6;
reg [31:0] main_preheaderi_6_reg;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_preheaderi_7;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_preheaderi_7_reg;
reg [7:0] main_preheaderi_8;
reg [7:0] main_preheaderi_8_reg;
reg [31:0] main_preheaderi_9;
reg [31:0] main_preheaderi_9_reg;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_preheaderi_10;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_preheaderi_10_reg;
reg [7:0] main_preheaderi_11;
reg [7:0] main_preheaderi_11_reg;
reg [31:0] main_preheaderi_12;
reg [31:0] main_preheaderi_12_reg;
reg [31:0] main_preheaderi_13;
reg [31:0] main_preheaderi_13_reg;
reg [31:0] main_preheaderi_14;
reg [31:0] main_preheaderi_14_reg;
reg [31:0] main_preheaderi_15;
reg [31:0] main_preheaderi_15_reg;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_preheaderi_16;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_preheaderi_16_reg;
reg [7:0] main_preheaderi_17;
reg [7:0] main_preheaderi_17_reg;
reg [31:0] main_preheaderi_18;
reg [31:0] main_preheaderi_18_reg;
reg [31:0] main_preheaderi_19;
reg [31:0] main_preheaderi_19_reg;
reg [31:0] main_preheaderi_20;
reg [31:0] main_preheaderi_20_reg;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_preheaderi_21;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_preheaderi_21_reg;
reg [7:0] main_preheaderi_22;
reg [7:0] main_preheaderi_22_reg;
reg [31:0] main_preheaderi_23;
reg [31:0] main_preheaderi_23_reg;
reg [31:0] main_preheaderi_24;
reg [31:0] main_preheaderi_24_reg;
reg [31:0] main_preheaderi_25;
reg [31:0] main_preheaderi_25_reg;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_preheaderi_26;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_preheaderi_26_reg;
reg [7:0] main_preheaderi_27;
reg [7:0] main_preheaderi_27_reg;
reg [31:0] main_preheaderi_28;
reg [31:0] main_preheaderi_28_reg;
reg [31:0] main_preheaderi_29;
reg [31:0] main_preheaderi_29_reg;
reg [31:0] main_preheaderi_30;
reg [31:0] main_preheaderi_30_reg;
reg [31:0] main_preheaderi_31;
reg [31:0] main_preheaderi_31_reg;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_preheaderi_32;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_preheaderi_32_reg;
reg [7:0] main_preheaderi_33;
reg [7:0] main_preheaderi_33_reg;
reg [31:0] main_preheaderi_34;
reg [31:0] main_preheaderi_34_reg;
reg [31:0] main_preheaderi_35;
reg [31:0] main_preheaderi_35_reg;
reg [31:0] main_preheaderi_36;
reg [31:0] main_preheaderi_36_reg;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_preheaderi_37;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_preheaderi_37_reg;
reg [7:0] main_preheaderi_38;
reg [7:0] main_preheaderi_38_reg;
reg [31:0] main_preheaderi_39;
reg [31:0] main_preheaderi_39_reg;
reg [31:0] main_preheaderi_40;
reg [31:0] main_preheaderi_40_reg;
reg [31:0] main_preheaderi_41;
reg [31:0] main_preheaderi_41_reg;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_preheaderi_42;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_preheaderi_42_reg;
reg [7:0] main_preheaderi_43;
reg [7:0] main_preheaderi_43_reg;
reg [31:0] main_preheaderi_44;
reg [31:0] main_preheaderi_44_reg;
reg [31:0] main_preheaderi_45;
reg [31:0] main_preheaderi_45_reg;
reg [31:0] main_preheaderi_46;
reg [31:0] main_preheaderi_46_reg;
reg  main_preheaderi_47;
reg  main_preheaderi_47_reg;
reg [31:0] main_preheaderi_48;
reg [31:0] main_preheaderi_48_reg;
reg [31:0] main_preheaderi_49;
reg [31:0] main_preheaderi_49_reg;
reg  main_preheaderi_50;
reg  main_preheaderi_50_reg;
reg [31:0] main_preheaderi_51;
reg [31:0] main_preheaderi_51_reg;
reg [31:0] main_preheaderi_52;
reg [31:0] main_preheaderi_52_reg;
reg [31:0] main_preheaderi_53;
reg [31:0] main_preheaderi_53_reg;
reg  main_preheaderi_54;
reg  main_preheaderi_54_reg;
reg [7:0] main_preheaderi_55;
reg [7:0] main_preheaderi_55_reg;
reg [7:0] main_preheaderi_56;
reg [7:0] main_preheaderi_56_reg;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_preheaderi_57;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_preheaderi_57_reg;
reg  main_preheaderi_exitcond9;
reg  main_preheaderi_exitcond9_reg;
reg [31:0] main_preheaderpreheader_crit_edgei_indvarnext8;
reg [31:0] main_preheaderpreheader_crit_edgei_indvarnext8_reg;
reg [31:0] main_preheader_indvar2;
reg [31:0] main_preheader_indvar2_reg;
reg [31:0] main_preheader_result03;
reg [31:0] main_preheader_result03_reg;
reg [31:0] main_preheader_58;
reg [31:0] main_preheader_58_reg;
reg [31:0] main_59_indvar;
reg [31:0] main_59_indvar_reg;
reg [31:0] main_59_result11;
reg [31:0] main_59_result11_reg;
reg [31:0] main_59_60;
reg [31:0] main_59_60_reg;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_59_scevgep4;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_59_scevgep4_reg;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_59_scevgep;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_59_scevgep_reg;
reg [7:0] main_59_61;
reg [7:0] main_59_61_reg;
reg [7:0] main_59_62;
reg [7:0] main_59_62_reg;
reg  main_59_not;
reg  main_59_not_reg;
reg [31:0] main_59_63;
reg [31:0] main_59_63_reg;
reg [31:0] main_59_result1;
reg [31:0] main_59_result1_reg;
reg [31:0] main_59_indvarnext;
reg [31:0] main_59_indvarnext_reg;
reg  main_59_exitcond1;
reg  main_59_exitcond1_reg;
reg [31:0] main_64_indvarnext3;
reg [31:0] main_64_indvarnext3_reg;
reg  main_64_exitcond;
reg  main_64_exitcond_reg;
reg  main_65_66;
reg  main_65_66_reg;
reg [17:0] elaine_512_input_address_a;
reg  elaine_512_input_write_enable_a;
wire [7:0] elaine_512_input_in_a;
wire [7:0] elaine_512_input_out_a;
reg [17:0] elaine_512_input_address_b;
reg  elaine_512_input_write_enable_b;
wire [7:0] elaine_512_input_in_b;
wire [7:0] elaine_512_input_out_b;
reg [17:0] elaine_512_golden_output_address_a;
reg  elaine_512_golden_output_write_enable_a;
wire [7:0] elaine_512_golden_output_in_a;
wire [7:0] elaine_512_golden_output_out_a;
wire [17:0] elaine_512_golden_output_address_b;
wire  elaine_512_golden_output_write_enable_b;
wire [7:0] elaine_512_golden_output_in_b;
wire [7:0] elaine_512_golden_output_out_b;
reg [17:0] main_0_sobel_output_address_a;
reg  main_0_sobel_output_write_enable_a;
reg [7:0] main_0_sobel_output_in_a;
wire [7:0] main_0_sobel_output_out_a;
wire [17:0] main_0_sobel_output_address_b;
wire  main_0_sobel_output_write_enable_b;
wire [7:0] main_0_sobel_output_in_b;
wire [7:0] main_0_sobel_output_out_b;
reg  loop1_1_pipeline_start;
reg  loop1_1_started;
reg  loop1_1_ii_state;
reg [31:0] loop1_1_i_stage0;
reg  loop1_1_epilogue;
reg  loop1_1_valid_bit_0;
reg  loop1_1_valid_bit_1;
reg  loop1_1_valid_bit_2;
reg  loop1_1_valid_bit_3;
reg [31:0] loop1_1_i_stage1;
reg [31:0] loop1_1_i_stage2;
reg [31:0] loop1_1_i_stage3;
reg [31:0] main_59_result11_reg_stage3;
reg [31:0] main_59_60_reg_stage1;
reg [31:0] main_59_63_reg_stage3;
reg [31:0] main_59_indvarnext_reg_stage1;
reg  loop1_1_pipeline_exit_cond;
reg  loop1_1_pipeline_finish;
reg  lpm_mult_main_preheaderi_13_en;
reg [31:0] main_preheaderi_13_stage0_reg;
reg  lpm_mult_main_preheaderi_29_en;
reg [31:0] main_preheaderi_29_stage0_reg;

always @(posedge start)
	$display("Cycle: %d Function: main Start", ($time-50)/20);
always@(posedge finish)
	$display("Cycle: %d Function: main Finish", ($time-50)/20);
// Local Rams


// @elaine_512_input = internal unnamed_addr constant [512 x [512 x i8]] [[512 x i8] c"\BE\BE\BE\BE\BE\C0\C0\C0\C0\C0\BC\BC\BC\BC\BC\B7\B7\B7\B7\B7\B9\B9\B9\B9\B9\B9\B9\B9\B9\B9\B7\B7\B7\B7\B7\B4\B4\B4\B...
rom_dual_port elaine_512_input (
	.clk( clk ),
	.clken( !memory_controller_waitrequest ),
	.address_a( elaine_512_input_address_a ),
	.address_b( elaine_512_input_address_b ),
	.q_a( elaine_512_input_out_a ),
	.q_b( elaine_512_input_out_b)
);
defparam elaine_512_input.width_a = 8;
defparam elaine_512_input.width_b = 8;
defparam elaine_512_input.widthad_a = 18;
defparam elaine_512_input.widthad_b = 18;
defparam elaine_512_input.numwords_a = 262144;
defparam elaine_512_input.numwords_b = 262144;
defparam elaine_512_input.latency = 1;
defparam elaine_512_input.init_file = "elaine_512_input.mif";


// @elaine_512_golden_output = internal unnamed_addr constant [512 x [512 x i8]] [[512 x i8] zeroinitializer, [512 x i8] c"\00\00\00\00\08\08\00\00\00\10\10\00\00\00\14\14\00\00\00\08\08\00\00\00\00\00\0...
rom_dual_port elaine_512_golden_output (
	.clk( clk ),
	.clken( !memory_controller_waitrequest ),
	.address_a( elaine_512_golden_output_address_a ),
	.address_b( elaine_512_golden_output_address_b ),
	.q_a( elaine_512_golden_output_out_a ),
	.q_b( elaine_512_golden_output_out_b)
);
defparam elaine_512_golden_output.width_a = 8;
defparam elaine_512_golden_output.width_b = 8;
defparam elaine_512_golden_output.widthad_a = 18;
defparam elaine_512_golden_output.widthad_b = 18;
defparam elaine_512_golden_output.numwords_a = 262144;
defparam elaine_512_golden_output.numwords_b = 262144;
defparam elaine_512_golden_output.latency = 1;
defparam elaine_512_golden_output.init_file = "elaine_512_golden_output.mif";


//   %sobel_output = alloca [512 x [512 x i8]], align 1
ram_dual_port main_0_sobel_output (
	.clk( clk ),
	.clken( !memory_controller_waitrequest ),
	.address_a( main_0_sobel_output_address_a ),
	.address_b( main_0_sobel_output_address_b ),
	.wren_a( main_0_sobel_output_write_enable_a ),
	.wren_b( main_0_sobel_output_write_enable_b ),
	.data_a( main_0_sobel_output_in_a ),
	.data_b( main_0_sobel_output_in_b ),
	.byteena_a( 1'b1 ),
	.byteena_b( 1'b1 ),
	.q_a( main_0_sobel_output_out_a ),
	.q_b( main_0_sobel_output_out_b)
);
defparam main_0_sobel_output.width_a = 8;
defparam main_0_sobel_output.width_b = 8;
defparam main_0_sobel_output.widthad_a = 18;
defparam main_0_sobel_output.widthad_b = 18;
defparam main_0_sobel_output.width_be_a = 1;
defparam main_0_sobel_output.width_be_b = 1;
defparam main_0_sobel_output.numwords_a = 262144;
defparam main_0_sobel_output.numwords_b = 262144;
defparam main_0_sobel_output.latency = 1;


/* Unsynthesizable Statements */
always @(posedge clk)
	if (!memory_controller_waitrequest) begin
	/* main: %67*/
	/*   %68 = tail call i32 (i8*, ...)* @printf(i8* getelementptr inbounds ([7 x i8]* @.str2, i32 0, i32 0)) #2*/
	if ((cur_state == LEGUP_F_main_BB__67_25)) begin
		$write("PASS!\n");
	end
	/* main: %69*/
	/*   %70 = tail call i32 (i8*, ...)* @printf(i8* getelementptr inbounds ([26 x i8]* @.str3, i32 0, i32 0), i32 %result.1.) #2*/
	if ((cur_state == LEGUP_F_main_BB__69_26)) begin
		$write("FAIL with %d differences\n", $signed(main_59_result1_reg));
		// to fix quartus warning
		if (reset == 1'b0 && ^(main_59_result1_reg) === 1'bX) finish <= 0;
	end
end
always @(posedge clk) begin
if (reset == 1'b1)
	cur_state <= LEGUP_0;
else if (memory_controller_waitrequest == 1'd1)
	cur_state <= cur_state;
else
	cur_state <= next_state;
end

always @(*)
begin
next_state = cur_state;
case(cur_state)  // synthesis parallel_case  
LEGUP_0:
	if ((start == 1'd1))
		next_state = LEGUP_F_main_BB__0_1;
LEGUP_F_main_BB__0_1:
		next_state = LEGUP_F_main_BB_preheaderi_2;
LEGUP_F_main_BB__64_22:
		next_state = LEGUP_F_main_BB__64_23;
LEGUP_F_main_BB__64_23:
	if ((main_64_exitcond == 1'd1))
		next_state = LEGUP_F_main_BB__65_24;
	else if ((main_64_exitcond == 1'd0))
		next_state = LEGUP_F_main_BB_preheader_20;
LEGUP_F_main_BB__65_24:
	if ((main_65_66 == 1'd1))
		next_state = LEGUP_F_main_BB__67_25;
	else if ((main_65_66 == 1'd0))
		next_state = LEGUP_F_main_BB__69_26;
LEGUP_F_main_BB__67_25:
		next_state = LEGUP_F_main_BB__71_27;
LEGUP_F_main_BB__69_26:
		next_state = LEGUP_F_main_BB__71_27;
LEGUP_F_main_BB__71_27:
		next_state = LEGUP_0;
LEGUP_F_main_BB_preheader_20:
		next_state = LEGUP_loop_pipeline_wait_loop1_1_21;
LEGUP_F_main_BB_preheaderi_10:
		next_state = LEGUP_F_main_BB_preheaderi_11;
LEGUP_F_main_BB_preheaderi_11:
		next_state = LEGUP_F_main_BB_preheaderi_12;
LEGUP_F_main_BB_preheaderi_12:
		next_state = LEGUP_F_main_BB_preheaderi_13;
LEGUP_F_main_BB_preheaderi_13:
		next_state = LEGUP_F_main_BB_preheaderi_14;
LEGUP_F_main_BB_preheaderi_14:
		next_state = LEGUP_F_main_BB_preheaderi_15;
LEGUP_F_main_BB_preheaderi_15:
		next_state = LEGUP_F_main_BB_preheaderi_16;
LEGUP_F_main_BB_preheaderi_16:
		next_state = LEGUP_F_main_BB_preheaderi_17;
LEGUP_F_main_BB_preheaderi_17:
	if ((main_preheaderi_exitcond9_reg == 1'd1))
		next_state = LEGUP_F_main_BB_preheaderpreheader_18;
	else if ((main_preheaderi_exitcond9_reg == 1'd0))
		next_state = LEGUP_F_main_BB_preheaderpreheader_crit_edgei_19;
LEGUP_F_main_BB_preheaderi_2:
		next_state = LEGUP_F_main_BB_preheaderi_3;
LEGUP_F_main_BB_preheaderi_3:
		next_state = LEGUP_F_main_BB_preheaderi_4;
LEGUP_F_main_BB_preheaderi_4:
		next_state = LEGUP_F_main_BB_preheaderi_5;
LEGUP_F_main_BB_preheaderi_5:
		next_state = LEGUP_F_main_BB_preheaderi_6;
LEGUP_F_main_BB_preheaderi_6:
		next_state = LEGUP_F_main_BB_preheaderi_7;
LEGUP_F_main_BB_preheaderi_7:
		next_state = LEGUP_F_main_BB_preheaderi_8;
LEGUP_F_main_BB_preheaderi_8:
		next_state = LEGUP_F_main_BB_preheaderi_9;
LEGUP_F_main_BB_preheaderi_9:
		next_state = LEGUP_F_main_BB_preheaderi_10;
LEGUP_F_main_BB_preheaderpreheader_18:
		next_state = LEGUP_F_main_BB_preheader_20;
LEGUP_F_main_BB_preheaderpreheader_crit_edgei_19:
		next_state = LEGUP_F_main_BB_preheaderi_2;
LEGUP_loop_pipeline_wait_loop1_1_21:
	if ((loop1_1_pipeline_finish == 1'd1))
		next_state = LEGUP_F_main_BB__64_22;
	else if ((loop1_1_pipeline_finish == 1'd1))
		next_state = LEGUP_F_main_BB__64_22;
default:
	next_state = cur_state;
endcase

end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %indvar7 = phi i32 [ %indvar.next8, %.preheader..preheader_crit_edge.i ], [ 0, %0 ]*/
	if (((cur_state == LEGUP_F_main_BB__0_1) & (memory_controller_waitrequest == 1'd0))) begin
		main_preheaderi_indvar7 = 32'd0;
	end
	/* main: %.preheader.i*/
	/*   %indvar7 = phi i32 [ %indvar.next8, %.preheader..preheader_crit_edge.i ], [ 0, %0 ]*/
	else /* if (((cur_state == LEGUP_F_main_BB_preheaderpreheader_crit_edgei_19) & (memory_controller_waitrequest == 1'd0))) */ begin
		main_preheaderi_indvar7 = main_preheaderpreheader_crit_edgei_indvarnext8;
	end
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %indvar7 = phi i32 [ %indvar.next8, %.preheader..preheader_crit_edge.i ], [ 0, %0 ]*/
	if (((cur_state == LEGUP_F_main_BB__0_1) & (memory_controller_waitrequest == 1'd0))) begin
		main_preheaderi_indvar7_reg <= main_preheaderi_indvar7;
		if (start == 1'b0 && ^(main_preheaderi_indvar7) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_indvar7_reg"); $finish; end
	end
	/* main: %.preheader.i*/
	/*   %indvar7 = phi i32 [ %indvar.next8, %.preheader..preheader_crit_edge.i ], [ 0, %0 ]*/
	if (((cur_state == LEGUP_F_main_BB_preheaderpreheader_crit_edgei_19) & (memory_controller_waitrequest == 1'd0))) begin
		main_preheaderi_indvar7_reg <= main_preheaderi_indvar7;
		if (start == 1'b0 && ^(main_preheaderi_indvar7) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_indvar7_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %y.08.i = phi i32 [ %3, %.preheader..preheader_crit_edge.i ], [ 1, %0 ]*/
	if (((cur_state == LEGUP_F_main_BB__0_1) & (memory_controller_waitrequest == 1'd0))) begin
		main_preheaderi_y08i = 32'd1;
	end
	/* main: %.preheader.i*/
	/*   %y.08.i = phi i32 [ %3, %.preheader..preheader_crit_edge.i ], [ 1, %0 ]*/
	else /* if (((cur_state == LEGUP_F_main_BB_preheaderpreheader_crit_edgei_19) & (memory_controller_waitrequest == 1'd0))) */ begin
		main_preheaderi_y08i = main_preheaderi_3_reg;
	end
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %y.08.i = phi i32 [ %3, %.preheader..preheader_crit_edge.i ], [ 1, %0 ]*/
	if (((cur_state == LEGUP_F_main_BB__0_1) & (memory_controller_waitrequest == 1'd0))) begin
		main_preheaderi_y08i_reg <= main_preheaderi_y08i;
		if (start == 1'b0 && ^(main_preheaderi_y08i) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_y08i_reg"); $finish; end
	end
	/* main: %.preheader.i*/
	/*   %y.08.i = phi i32 [ %3, %.preheader..preheader_crit_edge.i ], [ 1, %0 ]*/
	if (((cur_state == LEGUP_F_main_BB_preheaderpreheader_crit_edgei_19) & (memory_controller_waitrequest == 1'd0))) begin
		main_preheaderi_y08i_reg <= main_preheaderi_y08i;
		if (start == 1'b0 && ^(main_preheaderi_y08i) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_y08i_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %x.07.i = phi i32 [ %..i, %.preheader..preheader_crit_edge.i ], [ 0, %0 ]*/
	if (((cur_state == LEGUP_F_main_BB__0_1) & (memory_controller_waitrequest == 1'd0))) begin
		main_preheaderi_x07i = 32'd0;
	end
	/* main: %.preheader.i*/
	/*   %x.07.i = phi i32 [ %..i, %.preheader..preheader_crit_edge.i ], [ 0, %0 ]*/
	else /* if (((cur_state == LEGUP_F_main_BB_preheaderpreheader_crit_edgei_19) & (memory_controller_waitrequest == 1'd0))) */ begin
		main_preheaderi_x07i = main_preheaderi_i_reg;
	end
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %x.07.i = phi i32 [ %..i, %.preheader..preheader_crit_edge.i ], [ 0, %0 ]*/
	if (((cur_state == LEGUP_F_main_BB__0_1) & (memory_controller_waitrequest == 1'd0))) begin
		main_preheaderi_x07i_reg <= main_preheaderi_x07i;
		if (start == 1'b0 && ^(main_preheaderi_x07i) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_x07i_reg"); $finish; end
	end
	/* main: %.preheader.i*/
	/*   %x.07.i = phi i32 [ %..i, %.preheader..preheader_crit_edge.i ], [ 0, %0 ]*/
	if (((cur_state == LEGUP_F_main_BB_preheaderpreheader_crit_edgei_19) & (memory_controller_waitrequest == 1'd0))) begin
		main_preheaderi_x07i_reg <= main_preheaderi_x07i;
		if (start == 1'b0 && ^(main_preheaderi_x07i) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_x07i_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %1 = icmp eq i32 %x.07.i, 510*/
		main_preheaderi_1 = (main_preheaderi_x07i_reg == 32'd510);
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %1 = icmp eq i32 %x.07.i, 510*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_2)) begin
		main_preheaderi_1_reg <= main_preheaderi_1;
		if (start == 1'b0 && ^(main_preheaderi_1) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_1_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %2 = zext i1 %1 to i32*/
		main_preheaderi_2 = main_preheaderi_1;
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %2 = zext i1 %1 to i32*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_2)) begin
		main_preheaderi_2_reg <= main_preheaderi_2;
		if (start == 1'b0 && ^(main_preheaderi_2) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_2_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %3 = add nsw i32 %2, %y.08.i*/
		main_preheaderi_3 = (main_preheaderi_2_reg + main_preheaderi_y08i_reg);
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %3 = add nsw i32 %2, %y.08.i*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_3)) begin
		main_preheaderi_3_reg <= main_preheaderi_3;
		if (start == 1'b0 && ^(main_preheaderi_3) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_3_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %4 = add nsw i32 %x.07.i, 1*/
		main_preheaderi_4 = (main_preheaderi_x07i_reg + 32'd1);
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %4 = add nsw i32 %x.07.i, 1*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_2)) begin
		main_preheaderi_4_reg <= main_preheaderi_4;
		if (start == 1'b0 && ^(main_preheaderi_4) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_4_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %..i = select i1 %1, i32 1, i32 %4*/
		main_preheaderi_i = (main_preheaderi_1_reg ? 32'd1 : main_preheaderi_4_reg);
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %..i = select i1 %1, i32 1, i32 %4*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_3)) begin
		main_preheaderi_i_reg <= main_preheaderi_i;
		if (start == 1'b0 && ^(main_preheaderi_i) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_i_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %5 = add nsw i32 %..i, -1*/
		main_preheaderi_5 = (main_preheaderi_i_reg + -32'd1);
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %5 = add nsw i32 %..i, -1*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_4)) begin
		main_preheaderi_5_reg <= main_preheaderi_5;
		if (start == 1'b0 && ^(main_preheaderi_5) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_5_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %6 = add nsw i32 %3, -1*/
		main_preheaderi_6 = (main_preheaderi_3_reg + -32'd1);
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %6 = add nsw i32 %3, -1*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_4)) begin
		main_preheaderi_6_reg <= main_preheaderi_6;
		if (start == 1'b0 && ^(main_preheaderi_6) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_6_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %7 = getelementptr inbounds [512 x [512 x i8]]* @elaine_512_input, i32 0, i32 %6, i32 %5*/
		main_preheaderi_7 = (1'd0 | ((512 * main_preheaderi_6_reg) + (1 * main_preheaderi_5_reg)));
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %7 = getelementptr inbounds [512 x [512 x i8]]* @elaine_512_input, i32 0, i32 %6, i32 %5*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_5)) begin
		main_preheaderi_7_reg <= main_preheaderi_7;
		if (start == 1'b0 && ^(main_preheaderi_7) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_7_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %8 = load i8* %7, align 1, !tbaa !2*/
		main_preheaderi_8 = elaine_512_input_out_a;
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %8 = load i8* %7, align 1, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_6)) begin
		main_preheaderi_8_reg <= main_preheaderi_8;
		if (start == 1'b0 && ^(main_preheaderi_8) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_8_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %9 = zext i8 %8 to i32*/
		main_preheaderi_9 = main_preheaderi_8;
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %9 = zext i8 %8 to i32*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_6)) begin
		main_preheaderi_9_reg <= main_preheaderi_9;
		if (start == 1'b0 && ^(main_preheaderi_9) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_9_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %10 = getelementptr inbounds [512 x [512 x i8]]* @elaine_512_input, i32 0, i32 %6, i32 %..i*/
		main_preheaderi_10 = (1'd0 | ((512 * main_preheaderi_6_reg) + (1 * main_preheaderi_i_reg)));
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %10 = getelementptr inbounds [512 x [512 x i8]]* @elaine_512_input, i32 0, i32 %6, i32 %..i*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_5)) begin
		main_preheaderi_10_reg <= main_preheaderi_10;
		if (start == 1'b0 && ^(main_preheaderi_10) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_10_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %11 = load i8* %10, align 1, !tbaa !2*/
		main_preheaderi_11 = elaine_512_input_out_b;
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %11 = load i8* %10, align 1, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_6)) begin
		main_preheaderi_11_reg <= main_preheaderi_11;
		if (start == 1'b0 && ^(main_preheaderi_11) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_11_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %12 = zext i8 %11 to i32*/
		main_preheaderi_12 = main_preheaderi_11;
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %12 = zext i8 %11 to i32*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_6)) begin
		main_preheaderi_12_reg <= main_preheaderi_12;
		if (start == 1'b0 && ^(main_preheaderi_12) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_12_reg"); $finish; end
	end
end
always @(*) begin
	main_preheaderi_13 = main_preheaderi_13_stage0_reg;
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %13 = mul nsw i32 %12, -2*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_7)) begin
		main_preheaderi_13_reg <= main_preheaderi_13;
		if (start == 1'b0 && ^(main_preheaderi_13) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_13_reg"); $finish; end
	end
	/* main: %.preheader.i*/
	/*   %13 = mul nsw i32 %12, -2*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_7)) begin
		main_preheaderi_13_reg <= main_preheaderi_13;
		if (start == 1'b0 && ^(main_preheaderi_13) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_13_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %14 = sub i32 %13, %9*/
		main_preheaderi_14 = (main_preheaderi_13 - main_preheaderi_9_reg);
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %14 = sub i32 %13, %9*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_7)) begin
		main_preheaderi_14_reg <= main_preheaderi_14;
		if (start == 1'b0 && ^(main_preheaderi_14) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_14_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %15 = add nsw i32 %..i, 1*/
		main_preheaderi_15 = (main_preheaderi_i_reg + 32'd1);
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %15 = add nsw i32 %..i, 1*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_4)) begin
		main_preheaderi_15_reg <= main_preheaderi_15;
		if (start == 1'b0 && ^(main_preheaderi_15) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_15_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %16 = getelementptr inbounds [512 x [512 x i8]]* @elaine_512_input, i32 0, i32 %6, i32 %15*/
		main_preheaderi_16 = (1'd0 | ((512 * main_preheaderi_6_reg) + (1 * main_preheaderi_15_reg)));
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %16 = getelementptr inbounds [512 x [512 x i8]]* @elaine_512_input, i32 0, i32 %6, i32 %15*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_5)) begin
		main_preheaderi_16_reg <= main_preheaderi_16;
		if (start == 1'b0 && ^(main_preheaderi_16) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_16_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %17 = load i8* %16, align 1, !tbaa !2*/
		main_preheaderi_17 = elaine_512_input_out_a;
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %17 = load i8* %16, align 1, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_7)) begin
		main_preheaderi_17_reg <= main_preheaderi_17;
		if (start == 1'b0 && ^(main_preheaderi_17) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_17_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %18 = zext i8 %17 to i32*/
		main_preheaderi_18 = main_preheaderi_17;
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %18 = zext i8 %17 to i32*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_7)) begin
		main_preheaderi_18_reg <= main_preheaderi_18;
		if (start == 1'b0 && ^(main_preheaderi_18) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_18_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %19 = sub i32 %14, %18*/
		main_preheaderi_19 = (main_preheaderi_14_reg - main_preheaderi_18_reg);
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %19 = sub i32 %14, %18*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_8)) begin
		main_preheaderi_19_reg <= main_preheaderi_19;
		if (start == 1'b0 && ^(main_preheaderi_19) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_19_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %20 = sub i32 %9, %18*/
		main_preheaderi_20 = (main_preheaderi_9_reg - main_preheaderi_18);
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %20 = sub i32 %9, %18*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_7)) begin
		main_preheaderi_20_reg <= main_preheaderi_20;
		if (start == 1'b0 && ^(main_preheaderi_20) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_20_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %21 = getelementptr inbounds [512 x [512 x i8]]* @elaine_512_input, i32 0, i32 %3, i32 %5*/
		main_preheaderi_21 = (1'd0 | ((512 * main_preheaderi_3_reg) + (1 * main_preheaderi_5_reg)));
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %21 = getelementptr inbounds [512 x [512 x i8]]* @elaine_512_input, i32 0, i32 %3, i32 %5*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_5)) begin
		main_preheaderi_21_reg <= main_preheaderi_21;
		if (start == 1'b0 && ^(main_preheaderi_21) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_21_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %22 = load i8* %21, align 1, !tbaa !2*/
		main_preheaderi_22 = elaine_512_input_out_b;
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %22 = load i8* %21, align 1, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_7)) begin
		main_preheaderi_22_reg <= main_preheaderi_22;
		if (start == 1'b0 && ^(main_preheaderi_22) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_22_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %23 = zext i8 %22 to i32*/
		main_preheaderi_23 = main_preheaderi_22;
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %23 = zext i8 %22 to i32*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_7)) begin
		main_preheaderi_23_reg <= main_preheaderi_23;
		if (start == 1'b0 && ^(main_preheaderi_23) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_23_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %24 = shl nuw nsw i32 %23, 1*/
		main_preheaderi_24 = (main_preheaderi_23 <<< (32'd1 % 32));
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %24 = shl nuw nsw i32 %23, 1*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_7)) begin
		main_preheaderi_24_reg <= main_preheaderi_24;
		if (start == 1'b0 && ^(main_preheaderi_24) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_24_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %25 = add nsw i32 %24, %20*/
		main_preheaderi_25 = (main_preheaderi_24_reg + main_preheaderi_20_reg);
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %25 = add nsw i32 %24, %20*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_8)) begin
		main_preheaderi_25_reg <= main_preheaderi_25;
		if (start == 1'b0 && ^(main_preheaderi_25) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_25_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %26 = getelementptr inbounds [512 x [512 x i8]]* @elaine_512_input, i32 0, i32 %3, i32 %15*/
		main_preheaderi_26 = (1'd0 | ((512 * main_preheaderi_3_reg) + (1 * main_preheaderi_15_reg)));
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %26 = getelementptr inbounds [512 x [512 x i8]]* @elaine_512_input, i32 0, i32 %3, i32 %15*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_5)) begin
		main_preheaderi_26_reg <= main_preheaderi_26;
		if (start == 1'b0 && ^(main_preheaderi_26) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_26_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %27 = load i8* %26, align 1, !tbaa !2*/
		main_preheaderi_27 = elaine_512_input_out_a;
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %27 = load i8* %26, align 1, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_8)) begin
		main_preheaderi_27_reg <= main_preheaderi_27;
		if (start == 1'b0 && ^(main_preheaderi_27) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_27_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %28 = zext i8 %27 to i32*/
		main_preheaderi_28 = main_preheaderi_27;
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %28 = zext i8 %27 to i32*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_8)) begin
		main_preheaderi_28_reg <= main_preheaderi_28;
		if (start == 1'b0 && ^(main_preheaderi_28) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_28_reg"); $finish; end
	end
end
always @(*) begin
	main_preheaderi_29 = main_preheaderi_29_stage0_reg;
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %29 = mul nsw i32 %28, -2*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_9)) begin
		main_preheaderi_29_reg <= main_preheaderi_29;
		if (start == 1'b0 && ^(main_preheaderi_29) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_29_reg"); $finish; end
	end
	/* main: %.preheader.i*/
	/*   %29 = mul nsw i32 %28, -2*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_9)) begin
		main_preheaderi_29_reg <= main_preheaderi_29;
		if (start == 1'b0 && ^(main_preheaderi_29) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_29_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %30 = add nsw i32 %29, %25*/
		main_preheaderi_30 = (main_preheaderi_29 + main_preheaderi_25_reg);
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %30 = add nsw i32 %29, %25*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_9)) begin
		main_preheaderi_30_reg <= main_preheaderi_30;
		if (start == 1'b0 && ^(main_preheaderi_30) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_30_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %31 = add nsw i32 %3, 1*/
		main_preheaderi_31 = (main_preheaderi_3_reg + 32'd1);
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %31 = add nsw i32 %3, 1*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_4)) begin
		main_preheaderi_31_reg <= main_preheaderi_31;
		if (start == 1'b0 && ^(main_preheaderi_31) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_31_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %32 = getelementptr inbounds [512 x [512 x i8]]* @elaine_512_input, i32 0, i32 %31, i32 %5*/
		main_preheaderi_32 = (1'd0 | ((512 * main_preheaderi_31_reg) + (1 * main_preheaderi_5_reg)));
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %32 = getelementptr inbounds [512 x [512 x i8]]* @elaine_512_input, i32 0, i32 %31, i32 %5*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_5)) begin
		main_preheaderi_32_reg <= main_preheaderi_32;
		if (start == 1'b0 && ^(main_preheaderi_32) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_32_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %33 = load i8* %32, align 1, !tbaa !2*/
		main_preheaderi_33 = elaine_512_input_out_b;
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %33 = load i8* %32, align 1, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_8)) begin
		main_preheaderi_33_reg <= main_preheaderi_33;
		if (start == 1'b0 && ^(main_preheaderi_33) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_33_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %34 = zext i8 %33 to i32*/
		main_preheaderi_34 = main_preheaderi_33;
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %34 = zext i8 %33 to i32*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_8)) begin
		main_preheaderi_34_reg <= main_preheaderi_34;
		if (start == 1'b0 && ^(main_preheaderi_34) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_34_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %35 = add nsw i32 %34, %19*/
		main_preheaderi_35 = (main_preheaderi_34_reg + main_preheaderi_19_reg);
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %35 = add nsw i32 %34, %19*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_9)) begin
		main_preheaderi_35_reg <= main_preheaderi_35;
		if (start == 1'b0 && ^(main_preheaderi_35) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_35_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %36 = add nsw i32 %34, %30*/
		main_preheaderi_36 = (main_preheaderi_34_reg + main_preheaderi_30_reg);
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %36 = add nsw i32 %34, %30*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_10)) begin
		main_preheaderi_36_reg <= main_preheaderi_36;
		if (start == 1'b0 && ^(main_preheaderi_36) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_36_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %37 = getelementptr inbounds [512 x [512 x i8]]* @elaine_512_input, i32 0, i32 %31, i32 %..i*/
		main_preheaderi_37 = (1'd0 | ((512 * main_preheaderi_31_reg) + (1 * main_preheaderi_i_reg)));
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %37 = getelementptr inbounds [512 x [512 x i8]]* @elaine_512_input, i32 0, i32 %31, i32 %..i*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_5)) begin
		main_preheaderi_37_reg <= main_preheaderi_37;
		if (start == 1'b0 && ^(main_preheaderi_37) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_37_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %38 = load i8* %37, align 1, !tbaa !2*/
		main_preheaderi_38 = elaine_512_input_out_a;
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %38 = load i8* %37, align 1, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_9)) begin
		main_preheaderi_38_reg <= main_preheaderi_38;
		if (start == 1'b0 && ^(main_preheaderi_38) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_38_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %39 = zext i8 %38 to i32*/
		main_preheaderi_39 = main_preheaderi_38;
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %39 = zext i8 %38 to i32*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_9)) begin
		main_preheaderi_39_reg <= main_preheaderi_39;
		if (start == 1'b0 && ^(main_preheaderi_39) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_39_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %40 = shl nuw nsw i32 %39, 1*/
		main_preheaderi_40 = (main_preheaderi_39 <<< (32'd1 % 32));
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %40 = shl nuw nsw i32 %39, 1*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_9)) begin
		main_preheaderi_40_reg <= main_preheaderi_40;
		if (start == 1'b0 && ^(main_preheaderi_40) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_40_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %41 = add nsw i32 %40, %35*/
		main_preheaderi_41 = (main_preheaderi_40_reg + main_preheaderi_35_reg);
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %41 = add nsw i32 %40, %35*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_10)) begin
		main_preheaderi_41_reg <= main_preheaderi_41;
		if (start == 1'b0 && ^(main_preheaderi_41) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_41_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %42 = getelementptr inbounds [512 x [512 x i8]]* @elaine_512_input, i32 0, i32 %31, i32 %15*/
		main_preheaderi_42 = (1'd0 | ((512 * main_preheaderi_31_reg) + (1 * main_preheaderi_15_reg)));
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %42 = getelementptr inbounds [512 x [512 x i8]]* @elaine_512_input, i32 0, i32 %31, i32 %15*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_5)) begin
		main_preheaderi_42_reg <= main_preheaderi_42;
		if (start == 1'b0 && ^(main_preheaderi_42) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_42_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %43 = load i8* %42, align 1, !tbaa !2*/
		main_preheaderi_43 = elaine_512_input_out_b;
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %43 = load i8* %42, align 1, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_9)) begin
		main_preheaderi_43_reg <= main_preheaderi_43;
		if (start == 1'b0 && ^(main_preheaderi_43) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_43_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %44 = zext i8 %43 to i32*/
		main_preheaderi_44 = main_preheaderi_43;
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %44 = zext i8 %43 to i32*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_9)) begin
		main_preheaderi_44_reg <= main_preheaderi_44;
		if (start == 1'b0 && ^(main_preheaderi_44) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_44_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %45 = add nsw i32 %44, %41*/
		main_preheaderi_45 = (main_preheaderi_44_reg + main_preheaderi_41_reg);
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %45 = add nsw i32 %44, %41*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_11)) begin
		main_preheaderi_45_reg <= main_preheaderi_45;
		if (start == 1'b0 && ^(main_preheaderi_45) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_45_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %46 = sub i32 %36, %44*/
		main_preheaderi_46 = (main_preheaderi_36_reg - main_preheaderi_44_reg);
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %46 = sub i32 %36, %44*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_11)) begin
		main_preheaderi_46_reg <= main_preheaderi_46;
		if (start == 1'b0 && ^(main_preheaderi_46) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_46_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %47 = icmp slt i32 %45, 0*/
		main_preheaderi_47 = ($signed(main_preheaderi_45_reg) < $signed(32'd0));
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %47 = icmp slt i32 %45, 0*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_12)) begin
		main_preheaderi_47_reg <= main_preheaderi_47;
		if (start == 1'b0 && ^(main_preheaderi_47) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_47_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %48 = sub nsw i32 0, %45*/
		main_preheaderi_48 = (32'd0 - main_preheaderi_45_reg);
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %48 = sub nsw i32 0, %45*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_12)) begin
		main_preheaderi_48_reg <= main_preheaderi_48;
		if (start == 1'b0 && ^(main_preheaderi_48) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_48_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %49 = select i1 %47, i32 %48, i32 %45*/
		main_preheaderi_49 = (main_preheaderi_47_reg ? main_preheaderi_48_reg : main_preheaderi_45_reg);
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %49 = select i1 %47, i32 %48, i32 %45*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_13)) begin
		main_preheaderi_49_reg <= main_preheaderi_49;
		if (start == 1'b0 && ^(main_preheaderi_49) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_49_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %50 = icmp slt i32 %46, 0*/
		main_preheaderi_50 = ($signed(main_preheaderi_46_reg) < $signed(32'd0));
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %50 = icmp slt i32 %46, 0*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_12)) begin
		main_preheaderi_50_reg <= main_preheaderi_50;
		if (start == 1'b0 && ^(main_preheaderi_50) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_50_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %51 = sub nsw i32 0, %46*/
		main_preheaderi_51 = (32'd0 - main_preheaderi_46_reg);
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %51 = sub nsw i32 0, %46*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_12)) begin
		main_preheaderi_51_reg <= main_preheaderi_51;
		if (start == 1'b0 && ^(main_preheaderi_51) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_51_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %52 = select i1 %50, i32 %51, i32 %46*/
		main_preheaderi_52 = (main_preheaderi_50_reg ? main_preheaderi_51_reg : main_preheaderi_46_reg);
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %52 = select i1 %50, i32 %51, i32 %46*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_13)) begin
		main_preheaderi_52_reg <= main_preheaderi_52;
		if (start == 1'b0 && ^(main_preheaderi_52) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_52_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %53 = add nsw i32 %52, %49*/
		main_preheaderi_53 = (main_preheaderi_52_reg + main_preheaderi_49_reg);
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %53 = add nsw i32 %52, %49*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_14)) begin
		main_preheaderi_53_reg <= main_preheaderi_53;
		if (start == 1'b0 && ^(main_preheaderi_53) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_53_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %54 = icmp sgt i32 %53, 255*/
		main_preheaderi_54 = ($signed(main_preheaderi_53_reg) > $signed(32'd255));
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %54 = icmp sgt i32 %53, 255*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_15)) begin
		main_preheaderi_54_reg <= main_preheaderi_54;
		if (start == 1'b0 && ^(main_preheaderi_54) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_54_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %55 = trunc i32 %53 to i8*/
		main_preheaderi_55 = main_preheaderi_53[7:0];
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %55 = trunc i32 %53 to i8*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_14)) begin
		main_preheaderi_55_reg <= main_preheaderi_55;
		if (start == 1'b0 && ^(main_preheaderi_55) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_55_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %56 = select i1 %54, i8 -1, i8 %55*/
		main_preheaderi_56 = (main_preheaderi_54_reg ? -8'd1 : main_preheaderi_55_reg);
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %56 = select i1 %54, i8 -1, i8 %55*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_16)) begin
		main_preheaderi_56_reg <= main_preheaderi_56;
		if (start == 1'b0 && ^(main_preheaderi_56) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_56_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %57 = getelementptr inbounds [512 x [512 x i8]]* %sobel_output, i32 0, i32 %3, i32 %..i*/
		main_preheaderi_57 = (1'd0 | ((512 * main_preheaderi_3_reg) + (1 * main_preheaderi_i_reg)));
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %57 = getelementptr inbounds [512 x [512 x i8]]* %sobel_output, i32 0, i32 %3, i32 %..i*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_4)) begin
		main_preheaderi_57_reg <= main_preheaderi_57;
		if (start == 1'b0 && ^(main_preheaderi_57) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_57_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader.i*/
	/*   %exitcond9 = icmp eq i32 %indvar7, 260099*/
		main_preheaderi_exitcond9 = (main_preheaderi_indvar7_reg == 32'd260099);
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %exitcond9 = icmp eq i32 %indvar7, 260099*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_2)) begin
		main_preheaderi_exitcond9_reg <= main_preheaderi_exitcond9;
		if (start == 1'b0 && ^(main_preheaderi_exitcond9) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderi_exitcond9_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader..preheader_crit_edge.i*/
	/*   %indvar.next8 = add i32 %indvar7, 1*/
		main_preheaderpreheader_crit_edgei_indvarnext8 = (main_preheaderi_indvar7_reg + 32'd1);
end
always @(posedge clk) begin
	/* main: %.preheader..preheader_crit_edge.i*/
	/*   %indvar.next8 = add i32 %indvar7, 1*/
	if ((cur_state == LEGUP_F_main_BB_preheaderpreheader_crit_edgei_19)) begin
		main_preheaderpreheader_crit_edgei_indvarnext8_reg <= main_preheaderpreheader_crit_edgei_indvarnext8;
		if (start == 1'b0 && ^(main_preheaderpreheader_crit_edgei_indvarnext8) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheaderpreheader_crit_edgei_indvarnext8_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader*/
	/*   %indvar2 = phi i32 [ 0, %.preheader.preheader ], [ %indvar.next3, %64 ]*/
	if (((cur_state == LEGUP_F_main_BB_preheaderpreheader_18) & (memory_controller_waitrequest == 1'd0))) begin
		main_preheader_indvar2 = 32'd0;
	end
	/* main: %.preheader*/
	/*   %indvar2 = phi i32 [ 0, %.preheader.preheader ], [ %indvar.next3, %64 ]*/
	else /* if ((((cur_state == LEGUP_F_main_BB__64_23) & (memory_controller_waitrequest == 1'd0)) & (main_64_exitcond == 1'd0))) */ begin
		main_preheader_indvar2 = main_64_indvarnext3_reg;
	end
end
always @(posedge clk) begin
	/* main: %.preheader*/
	/*   %indvar2 = phi i32 [ 0, %.preheader.preheader ], [ %indvar.next3, %64 ]*/
	if (((cur_state == LEGUP_F_main_BB_preheaderpreheader_18) & (memory_controller_waitrequest == 1'd0))) begin
		main_preheader_indvar2_reg <= main_preheader_indvar2;
		if (start == 1'b0 && ^(main_preheader_indvar2) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheader_indvar2_reg"); $finish; end
	end
	/* main: %.preheader*/
	/*   %indvar2 = phi i32 [ 0, %.preheader.preheader ], [ %indvar.next3, %64 ]*/
	if ((((cur_state == LEGUP_F_main_BB__64_23) & (memory_controller_waitrequest == 1'd0)) & (main_64_exitcond == 1'd0))) begin
		main_preheader_indvar2_reg <= main_preheader_indvar2;
		if (start == 1'b0 && ^(main_preheader_indvar2) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheader_indvar2_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader*/
	/*   %result.03 = phi i32 [ 0, %.preheader.preheader ], [ %result.1., %64 ]*/
	if (((cur_state == LEGUP_F_main_BB_preheaderpreheader_18) & (memory_controller_waitrequest == 1'd0))) begin
		main_preheader_result03 = 32'd0;
	end
	/* main: %.preheader*/
	/*   %result.03 = phi i32 [ 0, %.preheader.preheader ], [ %result.1., %64 ]*/
	else /* if ((((cur_state == LEGUP_F_main_BB__64_23) & (memory_controller_waitrequest == 1'd0)) & (main_64_exitcond == 1'd0))) */ begin
		main_preheader_result03 = main_59_result1_reg;
	end
end
always @(posedge clk) begin
	/* main: %.preheader*/
	/*   %result.03 = phi i32 [ 0, %.preheader.preheader ], [ %result.1., %64 ]*/
	if (((cur_state == LEGUP_F_main_BB_preheaderpreheader_18) & (memory_controller_waitrequest == 1'd0))) begin
		main_preheader_result03_reg <= main_preheader_result03;
		if (start == 1'b0 && ^(main_preheader_result03) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheader_result03_reg"); $finish; end
	end
	/* main: %.preheader*/
	/*   %result.03 = phi i32 [ 0, %.preheader.preheader ], [ %result.1., %64 ]*/
	if ((((cur_state == LEGUP_F_main_BB__64_23) & (memory_controller_waitrequest == 1'd0)) & (main_64_exitcond == 1'd0))) begin
		main_preheader_result03_reg <= main_preheader_result03;
		if (start == 1'b0 && ^(main_preheader_result03) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheader_result03_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader*/
	/*   %58 = add i32 %indvar2, 1*/
		main_preheader_58 = (main_preheader_indvar2_reg + 32'd1);
end
always @(posedge clk) begin
	/* main: %.preheader*/
	/*   %58 = add i32 %indvar2, 1*/
	if ((cur_state == LEGUP_F_main_BB_preheader_20)) begin
		main_preheader_58_reg <= main_preheader_58;
		if (start == 1'b0 && ^(main_preheader_58) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheader_58_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %59*/
	/*   %indvar = phi i32 [ %indvar.next, %59 ], [ 0, %.preheader ], !legup.canonical_induction !5, !legup.pipeline.start_time !6, !legup.pipeline.avail_time !6, !legup.pipeline.stage !6
	start_time: 0 avail_time: 0 stage: 0 II: 1 start_ii_state = 0 % 1 = 0 avail_ii_state = 0 % 1 = 0*/
if (reset) begin main_59_indvar = 0; end
		main_59_indvar = 32'd0;
end
always @(posedge clk) begin
	/* main: %59*/
	/*   %indvar = phi i32 [ %indvar.next, %59 ], [ 0, %.preheader ], !legup.canonical_induction !5, !legup.pipeline.start_time !6, !legup.pipeline.avail_time !6, !legup.pipeline.stage !6
	start_time: 0 avail_time: 0 stage: 0 II: 1 start_ii_state = 0 % 1 = 0 avail_ii_state = 0 % 1 = 0*/
	if (((cur_state == LEGUP_F_main_BB_preheader_20) & (memory_controller_waitrequest == 1'd0))) begin
		main_59_indvar_reg <= main_59_indvar;
		if (start == 1'b0 && ^(main_59_indvar) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_59_indvar_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %59*/
	/*   %result.11 = phi i32 [ %result.1., %59 ], [ %result.03, %.preheader ], !legup.pipeline.start_time !7, !legup.pipeline.avail_time !7, !legup.pipeline.stage !7
	start_time: 2 avail_time: 2 stage: 2 II: 1 start_ii_state = 2 % 1 = 0 avail_ii_state = 2 % 1 = 0*/
	if (((memory_controller_waitrequest == 1'd0) & ((loop1_1_ii_state == 1'd0) & loop1_1_valid_bit_3))) begin
		main_59_result11 = main_59_result1;
	end
	/* main: %59*/
	/*   %result.11 = phi i32 [ %result.1., %59 ], [ %result.03, %.preheader ], !legup.pipeline.start_time !7, !legup.pipeline.avail_time !7, !legup.pipeline.stage !7
	start_time: 2 avail_time: 2 stage: 2 II: 1 start_ii_state = 2 % 1 = 0 avail_ii_state = 2 % 1 = 0*/
	else /* if (((cur_state == LEGUP_F_main_BB_preheader_20) & (memory_controller_waitrequest == 1'd0))) */ begin
		main_59_result11 = main_preheader_result03_reg;
	end
end
always @(posedge clk) begin
	/* main: %59*/
	/*   %result.11 = phi i32 [ %result.1., %59 ], [ %result.03, %.preheader ], !legup.pipeline.start_time !7, !legup.pipeline.avail_time !7, !legup.pipeline.stage !7
	start_time: 2 avail_time: 2 stage: 2 II: 1 start_ii_state = 2 % 1 = 0 avail_ii_state = 2 % 1 = 0*/
	if (((memory_controller_waitrequest == 1'd0) & ((loop1_1_ii_state == 1'd0) & loop1_1_valid_bit_3))) begin
		main_59_result11_reg <= main_59_result11;
		if (start == 1'b0 && ^(main_59_result11) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_59_result11_reg"); $finish; end
	end
	/* main: %59*/
	/*   %result.11 = phi i32 [ %result.1., %59 ], [ %result.03, %.preheader ], !legup.pipeline.start_time !7, !legup.pipeline.avail_time !7, !legup.pipeline.stage !7
	start_time: 2 avail_time: 2 stage: 2 II: 1 start_ii_state = 2 % 1 = 0 avail_ii_state = 2 % 1 = 0*/
	if (((cur_state == LEGUP_F_main_BB_preheader_20) & (memory_controller_waitrequest == 1'd0))) begin
		main_59_result11_reg <= main_59_result11;
		if (start == 1'b0 && ^(main_59_result11) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_59_result11_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %59*/
	/*   %60 = add i32 %indvar, 1, !legup.pipeline.start_time !6, !legup.pipeline.avail_time !6, !legup.pipeline.stage !6
	start_time: 0 avail_time: 0 stage: 0 II: 1 start_ii_state = 0 % 1 = 0 avail_ii_state = 0 % 1 = 0*/
		main_59_60 = (loop1_1_i_stage0 + 32'd1);
end
always @(posedge clk) begin
	/* main: %59*/
	/*   %60 = add i32 %indvar, 1, !legup.pipeline.start_time !6, !legup.pipeline.avail_time !6, !legup.pipeline.stage !6
	start_time: 0 avail_time: 0 stage: 0 II: 1 start_ii_state = 0 % 1 = 0 avail_ii_state = 0 % 1 = 0*/
	if ((~(memory_controller_waitrequest) & ((loop1_1_ii_state == 1'd0) & loop1_1_valid_bit_0))) begin
		main_59_60_reg <= main_59_60;
		if (start == 1'b0 && ^(main_59_60) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_59_60_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %59*/
	/*   %scevgep4 = getelementptr [512 x [512 x i8]]* %sobel_output, i32 0, i32 %58, i32 %60, !legup.pipeline.start_time !5, !legup.pipeline.avail_time !5, !legup.pipeline.stage !5
	start_time: 1 avail_time: 1 stage: 1 II: 1 start_ii_state = 1 % 1 = 0 avail_ii_state = 1 % 1 = 0*/
		main_59_scevgep4 = (1'd0 | ((512 * main_preheader_58_reg) + (1 * main_59_60_reg_stage1)));
end
always @(posedge clk) begin
	/* main: %59*/
	/*   %scevgep4 = getelementptr [512 x [512 x i8]]* %sobel_output, i32 0, i32 %58, i32 %60, !legup.pipeline.start_time !5, !legup.pipeline.avail_time !5, !legup.pipeline.stage !5
	start_time: 1 avail_time: 1 stage: 1 II: 1 start_ii_state = 1 % 1 = 0 avail_ii_state = 1 % 1 = 0*/
	if ((~(memory_controller_waitrequest) & ((loop1_1_ii_state == 1'd0) & loop1_1_valid_bit_1))) begin
		main_59_scevgep4_reg <= main_59_scevgep4;
		if (start == 1'b0 && ^(main_59_scevgep4) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_59_scevgep4_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %59*/
	/*   %scevgep = getelementptr [512 x [512 x i8]]* @elaine_512_golden_output, i32 0, i32 %58, i32 %60, !legup.pipeline.start_time !5, !legup.pipeline.avail_time !5, !legup.pipeline.stage !5
	start_time: 1 avail_time: 1 stage: 1 II: 1 start_ii_state = 1 % 1 = 0 avail_ii_state = 1 % 1 = 0*/
		main_59_scevgep = (1'd0 | ((512 * main_preheader_58_reg) + (1 * main_59_60_reg_stage1)));
end
always @(posedge clk) begin
	/* main: %59*/
	/*   %scevgep = getelementptr [512 x [512 x i8]]* @elaine_512_golden_output, i32 0, i32 %58, i32 %60, !legup.pipeline.start_time !5, !legup.pipeline.avail_time !5, !legup.pipeline.stage !5
	start_time: 1 avail_time: 1 stage: 1 II: 1 start_ii_state = 1 % 1 = 0 avail_ii_state = 1 % 1 = 0*/
	if ((~(memory_controller_waitrequest) & ((loop1_1_ii_state == 1'd0) & loop1_1_valid_bit_1))) begin
		main_59_scevgep_reg <= main_59_scevgep;
		if (start == 1'b0 && ^(main_59_scevgep) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_59_scevgep_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %59*/
	/*   %61 = load i8* %scevgep4, align 1, !tbaa !2, !legup.pipeline.start_time !5, !legup.pipeline.avail_time !7, !legup.pipeline.stage !5
	start_time: 1 avail_time: 2 stage: 1 II: 1 start_ii_state = 1 % 1 = 0 avail_ii_state = 2 % 1 = 0*/
		main_59_61 = main_0_sobel_output_out_a;
end
always @(posedge clk) begin
	/* main: %59*/
	/*   %61 = load i8* %scevgep4, align 1, !tbaa !2, !legup.pipeline.start_time !5, !legup.pipeline.avail_time !7, !legup.pipeline.stage !5
	start_time: 1 avail_time: 2 stage: 1 II: 1 start_ii_state = 1 % 1 = 0 avail_ii_state = 2 % 1 = 0*/
	if ((~(memory_controller_waitrequest) & ((loop1_1_ii_state == 1'd0) & loop1_1_valid_bit_2))) begin
		main_59_61_reg <= main_59_61;
		if (start == 1'b0 && ^(main_59_61) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_59_61_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %59*/
	/*   %62 = load i8* %scevgep, align 1, !tbaa !2, !legup.pipeline.start_time !5, !legup.pipeline.avail_time !7, !legup.pipeline.stage !5
	start_time: 1 avail_time: 2 stage: 1 II: 1 start_ii_state = 1 % 1 = 0 avail_ii_state = 2 % 1 = 0*/
		main_59_62 = elaine_512_golden_output_out_a;
end
always @(posedge clk) begin
	/* main: %59*/
	/*   %62 = load i8* %scevgep, align 1, !tbaa !2, !legup.pipeline.start_time !5, !legup.pipeline.avail_time !7, !legup.pipeline.stage !5
	start_time: 1 avail_time: 2 stage: 1 II: 1 start_ii_state = 1 % 1 = 0 avail_ii_state = 2 % 1 = 0*/
	if ((~(memory_controller_waitrequest) & ((loop1_1_ii_state == 1'd0) & loop1_1_valid_bit_2))) begin
		main_59_62_reg <= main_59_62;
		if (start == 1'b0 && ^(main_59_62) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_59_62_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %59*/
	/*   %not. = icmp ne i8 %61, %62, !legup.pipeline.start_time !7, !legup.pipeline.avail_time !7, !legup.pipeline.stage !7
	start_time: 2 avail_time: 2 stage: 2 II: 1 start_ii_state = 2 % 1 = 0 avail_ii_state = 2 % 1 = 0*/
		main_59_not = (main_59_61 != main_59_62);
end
always @(posedge clk) begin
	/* main: %59*/
	/*   %not. = icmp ne i8 %61, %62, !legup.pipeline.start_time !7, !legup.pipeline.avail_time !7, !legup.pipeline.stage !7
	start_time: 2 avail_time: 2 stage: 2 II: 1 start_ii_state = 2 % 1 = 0 avail_ii_state = 2 % 1 = 0*/
	if ((~(memory_controller_waitrequest) & ((loop1_1_ii_state == 1'd0) & loop1_1_valid_bit_2))) begin
		main_59_not_reg <= main_59_not;
		if (start == 1'b0 && ^(main_59_not) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_59_not_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %59*/
	/*   %63 = zext i1 %not. to i32, !legup.pipeline.start_time !7, !legup.pipeline.avail_time !7, !legup.pipeline.stage !7
	start_time: 2 avail_time: 2 stage: 2 II: 1 start_ii_state = 2 % 1 = 0 avail_ii_state = 2 % 1 = 0*/
		main_59_63 = main_59_not;
end
always @(posedge clk) begin
	/* main: %59*/
	/*   %63 = zext i1 %not. to i32, !legup.pipeline.start_time !7, !legup.pipeline.avail_time !7, !legup.pipeline.stage !7
	start_time: 2 avail_time: 2 stage: 2 II: 1 start_ii_state = 2 % 1 = 0 avail_ii_state = 2 % 1 = 0*/
	if ((~(memory_controller_waitrequest) & ((loop1_1_ii_state == 1'd0) & loop1_1_valid_bit_2))) begin
		main_59_63_reg <= main_59_63;
		if (start == 1'b0 && ^(main_59_63) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_59_63_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %59*/
	/*   %result.1. = add nsw i32 %63, %result.11, !legup.pipeline.start_time !8, !legup.pipeline.avail_time !8, !legup.pipeline.stage !8
	start_time: 3 avail_time: 3 stage: 3 II: 1 start_ii_state = 3 % 1 = 0 avail_ii_state = 3 % 1 = 0*/
		main_59_result1 = (main_59_63_reg_stage3 + main_59_result11_reg);
end
always @(posedge clk) begin
	/* main: %59*/
	/*   %result.1. = add nsw i32 %63, %result.11, !legup.pipeline.start_time !8, !legup.pipeline.avail_time !8, !legup.pipeline.stage !8
	start_time: 3 avail_time: 3 stage: 3 II: 1 start_ii_state = 3 % 1 = 0 avail_ii_state = 3 % 1 = 0*/
	if ((~(memory_controller_waitrequest) & ((loop1_1_ii_state == 1'd0) & loop1_1_valid_bit_3))) begin
		main_59_result1_reg <= main_59_result1;
		if (start == 1'b0 && ^(main_59_result1) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_59_result1_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %59*/
	/*   %indvar.next = add i32 %indvar, 1, !legup.pipeline.start_time !6, !legup.pipeline.avail_time !6, !legup.pipeline.stage !6
	start_time: 0 avail_time: 0 stage: 0 II: 1 start_ii_state = 0 % 1 = 0 avail_ii_state = 0 % 1 = 0*/
		main_59_indvarnext = (loop1_1_i_stage0 + 32'd1);
end
always @(posedge clk) begin
	/* main: %59*/
	/*   %indvar.next = add i32 %indvar, 1, !legup.pipeline.start_time !6, !legup.pipeline.avail_time !6, !legup.pipeline.stage !6
	start_time: 0 avail_time: 0 stage: 0 II: 1 start_ii_state = 0 % 1 = 0 avail_ii_state = 0 % 1 = 0*/
	if ((~(memory_controller_waitrequest) & ((loop1_1_ii_state == 1'd0) & loop1_1_valid_bit_0))) begin
		main_59_indvarnext_reg <= main_59_indvarnext;
		if (start == 1'b0 && ^(main_59_indvarnext) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_59_indvarnext_reg"); $finish; end
	end
end
always @(*) begin
		main_59_exitcond1 = loop1_1_pipeline_finish;
end
always @(posedge clk) begin
	if ((cur_state == LEGUP_loop_pipeline_wait_loop1_1_21)) begin
		main_59_exitcond1_reg <= loop1_1_pipeline_finish;
		if (start == 1'b0 && ^(loop1_1_pipeline_finish) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_59_exitcond1_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %64*/
	/*   %indvar.next3 = add i32 %indvar2, 1*/
		main_64_indvarnext3 = (main_preheader_indvar2_reg + 32'd1);
end
always @(posedge clk) begin
	/* main: %64*/
	/*   %indvar.next3 = add i32 %indvar2, 1*/
	if ((cur_state == LEGUP_F_main_BB__64_22)) begin
		main_64_indvarnext3_reg <= main_64_indvarnext3;
		if (start == 1'b0 && ^(main_64_indvarnext3) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_64_indvarnext3_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %64*/
	/*   %exitcond = icmp eq i32 %indvar.next3, 510*/
		main_64_exitcond = (main_64_indvarnext3_reg == 32'd510);
end
always @(posedge clk) begin
	/* main: %64*/
	/*   %exitcond = icmp eq i32 %indvar.next3, 510*/
	if ((cur_state == LEGUP_F_main_BB__64_23)) begin
		main_64_exitcond_reg <= main_64_exitcond;
		if (start == 1'b0 && ^(main_64_exitcond) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_64_exitcond_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %65*/
	/*   %66 = icmp eq i32 %result.1., 0*/
		main_65_66 = (main_59_result1_reg == 32'd0);
end
always @(posedge clk) begin
	/* main: %65*/
	/*   %66 = icmp eq i32 %result.1., 0*/
	if ((cur_state == LEGUP_F_main_BB__65_24)) begin
		main_65_66_reg <= main_65_66;
		if (start == 1'b0 && ^(main_65_66) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_65_66_reg"); $finish; end
	end
end
always @(*) begin
	elaine_512_input_address_a = 1'd0;
	/* main: %.preheader.i*/
	/*   %8 = load i8* %7, align 1, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_5)) begin
		elaine_512_input_address_a = (main_preheaderi_7 >>> 3'd0);
	end
	/* main: %.preheader.i*/
	/*   %17 = load i8* %16, align 1, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_6)) begin
		elaine_512_input_address_a = (main_preheaderi_16_reg >>> 3'd0);
	end
	/* main: %.preheader.i*/
	/*   %27 = load i8* %26, align 1, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_7)) begin
		elaine_512_input_address_a = (main_preheaderi_26_reg >>> 3'd0);
	end
	/* main: %.preheader.i*/
	/*   %38 = load i8* %37, align 1, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_8)) begin
		elaine_512_input_address_a = (main_preheaderi_37_reg >>> 3'd0);
	end
end
always @(*) begin
	elaine_512_input_write_enable_a = 1'd0;
	/* main: %.preheader.i*/
	/*   %8 = load i8* %7, align 1, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_5)) begin
		elaine_512_input_write_enable_a = 1'd0;
	end
	/* main: %.preheader.i*/
	/*   %17 = load i8* %16, align 1, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_6)) begin
		elaine_512_input_write_enable_a = 1'd0;
	end
	/* main: %.preheader.i*/
	/*   %27 = load i8* %26, align 1, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_7)) begin
		elaine_512_input_write_enable_a = 1'd0;
	end
	/* main: %.preheader.i*/
	/*   %38 = load i8* %37, align 1, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_8)) begin
		elaine_512_input_write_enable_a = 1'd0;
	end
end
always @(*) begin
	elaine_512_input_address_b = 1'd0;
	/* main: %.preheader.i*/
	/*   %11 = load i8* %10, align 1, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_5)) begin
		elaine_512_input_address_b = (main_preheaderi_10 >>> 3'd0);
	end
	/* main: %.preheader.i*/
	/*   %22 = load i8* %21, align 1, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_6)) begin
		elaine_512_input_address_b = (main_preheaderi_21_reg >>> 3'd0);
	end
	/* main: %.preheader.i*/
	/*   %33 = load i8* %32, align 1, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_7)) begin
		elaine_512_input_address_b = (main_preheaderi_32_reg >>> 3'd0);
	end
	/* main: %.preheader.i*/
	/*   %43 = load i8* %42, align 1, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_8)) begin
		elaine_512_input_address_b = (main_preheaderi_42_reg >>> 3'd0);
	end
end
always @(*) begin
	elaine_512_input_write_enable_b = 1'd0;
	/* main: %.preheader.i*/
	/*   %11 = load i8* %10, align 1, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_5)) begin
		elaine_512_input_write_enable_b = 1'd0;
	end
	/* main: %.preheader.i*/
	/*   %22 = load i8* %21, align 1, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_6)) begin
		elaine_512_input_write_enable_b = 1'd0;
	end
	/* main: %.preheader.i*/
	/*   %33 = load i8* %32, align 1, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_7)) begin
		elaine_512_input_write_enable_b = 1'd0;
	end
	/* main: %.preheader.i*/
	/*   %43 = load i8* %42, align 1, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_8)) begin
		elaine_512_input_write_enable_b = 1'd0;
	end
end
always @(*) begin
	elaine_512_golden_output_address_a = 1'd0;
	/* main: %59*/
	/*   %62 = load i8* %scevgep, align 1, !tbaa !2, !legup.pipeline.start_time !5, !legup.pipeline.avail_time !7, !legup.pipeline.stage !5
	start_time: 1 avail_time: 2 stage: 1 II: 1 start_ii_state = 1 % 1 = 0 avail_ii_state = 2 % 1 = 0*/
	if (((loop1_1_ii_state == 1'd0) & loop1_1_valid_bit_1)) begin
		elaine_512_golden_output_address_a = (main_59_scevgep >>> 3'd0);
	end
end
always @(*) begin
	elaine_512_golden_output_write_enable_a = 1'd0;
	/* main: %59*/
	/*   %62 = load i8* %scevgep, align 1, !tbaa !2, !legup.pipeline.start_time !5, !legup.pipeline.avail_time !7, !legup.pipeline.stage !5
	start_time: 1 avail_time: 2 stage: 1 II: 1 start_ii_state = 1 % 1 = 0 avail_ii_state = 2 % 1 = 0*/
	if (((loop1_1_ii_state == 1'd0) & loop1_1_valid_bit_1)) begin
		elaine_512_golden_output_write_enable_a = 1'd0;
	end
end
always @(*) begin
	main_0_sobel_output_address_a = 1'd0;
	/* main: %.preheader.i*/
	/*   store i8 %56, i8* %57, align 1, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_16)) begin
		main_0_sobel_output_address_a = (main_preheaderi_57_reg >>> 3'd0);
	end
	/* main: %59*/
	/*   %61 = load i8* %scevgep4, align 1, !tbaa !2, !legup.pipeline.start_time !5, !legup.pipeline.avail_time !7, !legup.pipeline.stage !5
	start_time: 1 avail_time: 2 stage: 1 II: 1 start_ii_state = 1 % 1 = 0 avail_ii_state = 2 % 1 = 0*/
	if (((loop1_1_ii_state == 1'd0) & loop1_1_valid_bit_1)) begin
		main_0_sobel_output_address_a = (main_59_scevgep4 >>> 3'd0);
	end
end
always @(*) begin
	main_0_sobel_output_write_enable_a = 1'd0;
	/* main: %.preheader.i*/
	/*   store i8 %56, i8* %57, align 1, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_16)) begin
		main_0_sobel_output_write_enable_a = 1'd1;
	end
	/* main: %59*/
	/*   %61 = load i8* %scevgep4, align 1, !tbaa !2, !legup.pipeline.start_time !5, !legup.pipeline.avail_time !7, !legup.pipeline.stage !5
	start_time: 1 avail_time: 2 stage: 1 II: 1 start_ii_state = 1 % 1 = 0 avail_ii_state = 2 % 1 = 0*/
	if (((loop1_1_ii_state == 1'd0) & loop1_1_valid_bit_1)) begin
		main_0_sobel_output_write_enable_a = 1'd0;
	end
end
always @(*) begin
	main_0_sobel_output_in_a = 1'd0;
	/* main: %.preheader.i*/
	/*   store i8 %56, i8* %57, align 1, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheaderi_16)) begin
		main_0_sobel_output_in_a = main_preheaderi_56;
	end
end
always @(*) begin
	loop1_1_pipeline_start = 1'd0;
	if (reset) begin
		loop1_1_pipeline_start = 1'd0;
	end
	if (((cur_state == LEGUP_F_main_BB_preheader_20) & (memory_controller_waitrequest == 1'd0))) begin
		loop1_1_pipeline_start = 1'd1;
	end
end
always @(posedge clk) begin
	if (reset) begin
		loop1_1_started <= 1'd0;
		if (start == 1'b0 && ^(1'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop1_1_started"); $finish; end
	end
	if (((memory_controller_waitrequest == 1'd0) & (loop1_1_pipeline_start & ~(loop1_1_started)))) begin
		loop1_1_started <= 1'd1;
		if (start == 1'b0 && ^(1'd1) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop1_1_started"); $finish; end
	end
	if (((memory_controller_waitrequest == 1'd0) & (loop1_1_epilogue & (~(loop1_1_valid_bit_2) & loop1_1_valid_bit_3)))) begin
		loop1_1_started <= 1'd0;
		if (start == 1'b0 && ^(1'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop1_1_started"); $finish; end
	end
end
always @(posedge clk) begin
	if (reset) begin
		loop1_1_ii_state <= 1'd0;
		if (start == 1'b0 && ^(1'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop1_1_ii_state"); $finish; end
	end
	if (((memory_controller_waitrequest == 1'd0) & (loop1_1_pipeline_start & ~(loop1_1_started)))) begin
		loop1_1_ii_state <= 1'd0;
		if (start == 1'b0 && ^(1'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop1_1_ii_state"); $finish; end
	end
	if (((memory_controller_waitrequest == 1'd0) & (loop1_1_ii_state == 1'd0))) begin
		loop1_1_ii_state <= 1'd0;
		if (start == 1'b0 && ^(1'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop1_1_ii_state"); $finish; end
	end
end
always @(posedge clk) begin
	if (reset) begin
		loop1_1_i_stage0 <= 0;
		if (start == 1'b0 && ^(0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop1_1_i_stage0"); $finish; end
	end
	if (((memory_controller_waitrequest == 1'd0) & (loop1_1_pipeline_start & ~(loop1_1_started)))) begin
		loop1_1_i_stage0 <= 0;
		if (start == 1'b0 && ^(0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop1_1_i_stage0"); $finish; end
	end
	if (((memory_controller_waitrequest == 1'd0) & (((memory_controller_waitrequest == 1'd0) & (loop1_1_ii_state == 1'd0)) & loop1_1_valid_bit_0))) begin
		loop1_1_i_stage0 <= (loop1_1_i_stage0 + 1'd1);
		if (start == 1'b0 && ^((loop1_1_i_stage0 + 1'd1)) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop1_1_i_stage0"); $finish; end
	end
	if (reset) begin
		loop1_1_i_stage0 <= 0;
		if (start == 1'b0 && ^(0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop1_1_i_stage0"); $finish; end
	end
end
always @(posedge clk) begin
	if (reset) begin
		loop1_1_epilogue <= 1'd0;
		if (start == 1'b0 && ^(1'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop1_1_epilogue"); $finish; end
	end
	if (((memory_controller_waitrequest == 1'd0) & (loop1_1_started & ((loop1_1_ii_state == 1'd0) & loop1_1_pipeline_exit_cond)))) begin
		loop1_1_epilogue <= 1'd1;
		if (start == 1'b0 && ^(1'd1) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop1_1_epilogue"); $finish; end
	end
	if (((memory_controller_waitrequest == 1'd0) & (loop1_1_epilogue & (~(loop1_1_valid_bit_2) & loop1_1_valid_bit_3)))) begin
		loop1_1_epilogue <= 1'd0;
		if (start == 1'b0 && ^(1'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop1_1_epilogue"); $finish; end
	end
end
always @(posedge clk) begin
	if ((memory_controller_waitrequest == 1'd0)) begin
		loop1_1_valid_bit_0 <= (((memory_controller_waitrequest == 1'd0) & (loop1_1_pipeline_start & ~(loop1_1_started))) | ((loop1_1_started & ~(loop1_1_epilogue)) & ~(((memory_controller_waitrequest == 1'd0) & (loop1_1_started & ((loop1_1_ii_state == 1'd0) & loop1_1_pipeline_exit_cond))))));
		if (start == 1'b0 && ^((((memory_controller_waitrequest == 1'd0) & (loop1_1_pipeline_start & ~(loop1_1_started))) | ((loop1_1_started & ~(loop1_1_epilogue)) & ~(((memory_controller_waitrequest == 1'd0) & (loop1_1_started & ((loop1_1_ii_state == 1'd0) & loop1_1_pipeline_exit_cond))))))) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop1_1_valid_bit_0"); $finish; end
	end
	if (reset) begin
		loop1_1_valid_bit_0 <= 1'd0;
		if (start == 1'b0 && ^(1'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop1_1_valid_bit_0"); $finish; end
	end
end
always @(posedge clk) begin
	if ((memory_controller_waitrequest == 1'd0)) begin
		loop1_1_valid_bit_1 <= loop1_1_valid_bit_0;
		if (start == 1'b0 && ^(loop1_1_valid_bit_0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop1_1_valid_bit_1"); $finish; end
	end
	if (reset) begin
		loop1_1_valid_bit_1 <= 1'd0;
		if (start == 1'b0 && ^(1'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop1_1_valid_bit_1"); $finish; end
	end
end
always @(posedge clk) begin
	if ((memory_controller_waitrequest == 1'd0)) begin
		loop1_1_valid_bit_2 <= loop1_1_valid_bit_1;
		if (start == 1'b0 && ^(loop1_1_valid_bit_1) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop1_1_valid_bit_2"); $finish; end
	end
	if (reset) begin
		loop1_1_valid_bit_2 <= 1'd0;
		if (start == 1'b0 && ^(1'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop1_1_valid_bit_2"); $finish; end
	end
end
always @(posedge clk) begin
	if ((memory_controller_waitrequest == 1'd0)) begin
		loop1_1_valid_bit_3 <= loop1_1_valid_bit_2;
		if (start == 1'b0 && ^(loop1_1_valid_bit_2) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop1_1_valid_bit_3"); $finish; end
	end
	if (reset) begin
		loop1_1_valid_bit_3 <= 1'd0;
		if (start == 1'b0 && ^(1'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop1_1_valid_bit_3"); $finish; end
	end
end
always @(posedge clk) begin
	if (((memory_controller_waitrequest == 1'd0) & (loop1_1_pipeline_start & ~(loop1_1_started)))) begin
		loop1_1_i_stage1 <= 0;
		if (start == 1'b0 && ^(0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop1_1_i_stage1"); $finish; end
	end
	if (((memory_controller_waitrequest == 1'd0) & (loop1_1_ii_state == 1'd0))) begin
		loop1_1_i_stage1 <= loop1_1_i_stage0;
		if (start == 1'b0 && ^(loop1_1_i_stage0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop1_1_i_stage1"); $finish; end
	end
	if (reset) begin
		loop1_1_i_stage1 <= 0;
		if (start == 1'b0 && ^(0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop1_1_i_stage1"); $finish; end
	end
end
always @(posedge clk) begin
	if (((memory_controller_waitrequest == 1'd0) & (loop1_1_pipeline_start & ~(loop1_1_started)))) begin
		loop1_1_i_stage2 <= 0;
		if (start == 1'b0 && ^(0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop1_1_i_stage2"); $finish; end
	end
	if (((memory_controller_waitrequest == 1'd0) & (loop1_1_ii_state == 1'd0))) begin
		loop1_1_i_stage2 <= loop1_1_i_stage1;
		if (start == 1'b0 && ^(loop1_1_i_stage1) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop1_1_i_stage2"); $finish; end
	end
	if (reset) begin
		loop1_1_i_stage2 <= 0;
		if (start == 1'b0 && ^(0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop1_1_i_stage2"); $finish; end
	end
end
always @(posedge clk) begin
	if (((memory_controller_waitrequest == 1'd0) & (loop1_1_pipeline_start & ~(loop1_1_started)))) begin
		loop1_1_i_stage3 <= 0;
		if (start == 1'b0 && ^(0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop1_1_i_stage3"); $finish; end
	end
	if (((memory_controller_waitrequest == 1'd0) & (loop1_1_ii_state == 1'd0))) begin
		loop1_1_i_stage3 <= loop1_1_i_stage2;
		if (start == 1'b0 && ^(loop1_1_i_stage2) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop1_1_i_stage3"); $finish; end
	end
	if (reset) begin
		loop1_1_i_stage3 <= 0;
		if (start == 1'b0 && ^(0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop1_1_i_stage3"); $finish; end
	end
end
always @(posedge clk) begin
	if (((memory_controller_waitrequest == 1'd0) & ((loop1_1_ii_state == 1'd0) & loop1_1_valid_bit_2))) begin
		main_59_result11_reg_stage3 <= main_59_result11;
		if (start == 1'b0 && ^(main_59_result11) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_59_result11_reg_stage3"); $finish; end
	end
end
always @(posedge clk) begin
	if (((memory_controller_waitrequest == 1'd0) & ((loop1_1_ii_state == 1'd0) & loop1_1_valid_bit_0))) begin
		main_59_60_reg_stage1 <= main_59_60;
		if (start == 1'b0 && ^(main_59_60) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_59_60_reg_stage1"); $finish; end
	end
end
always @(posedge clk) begin
	if (((memory_controller_waitrequest == 1'd0) & ((loop1_1_ii_state == 1'd0) & loop1_1_valid_bit_2))) begin
		main_59_63_reg_stage3 <= main_59_63;
		if (start == 1'b0 && ^(main_59_63) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_59_63_reg_stage3"); $finish; end
	end
end
always @(posedge clk) begin
	if (((memory_controller_waitrequest == 1'd0) & ((loop1_1_ii_state == 1'd0) & loop1_1_valid_bit_0))) begin
		main_59_indvarnext_reg_stage1 <= main_59_indvarnext;
		if (start == 1'b0 && ^(main_59_indvarnext) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_59_indvarnext_reg_stage1"); $finish; end
	end
end
always @(*) begin
	loop1_1_pipeline_exit_cond = (loop1_1_i_stage0 == 509);
end
always @(*) begin
	loop1_1_pipeline_finish = ((memory_controller_waitrequest == 1'd0) & (loop1_1_epilogue & (~(loop1_1_valid_bit_2) & loop1_1_valid_bit_3)));
end
always @(*) begin
	lpm_mult_main_preheaderi_13_en = (memory_controller_waitrequest == 1'd0);
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %13 = mul nsw i32 %12, -2*/
	if ((lpm_mult_main_preheaderi_13_en == 1'd1)) begin
		main_preheaderi_13_stage0_reg <= (main_preheaderi_12 * -32'd2);
	end
end
always @(*) begin
	lpm_mult_main_preheaderi_29_en = (memory_controller_waitrequest == 1'd0);
end
always @(posedge clk) begin
	/* main: %.preheader.i*/
	/*   %29 = mul nsw i32 %28, -2*/
	if ((lpm_mult_main_preheaderi_29_en == 1'd1)) begin
		main_preheaderi_29_stage0_reg <= (main_preheaderi_28 * -32'd2);
	end
end
always @(posedge clk) begin
	if ((cur_state == LEGUP_0)) begin
		finish <= 1'd0;
		if (start == 1'b0 && ^(1'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to finish"); $finish; end
	end
	/* main: %71*/
	/*   ret i32 %result.1.*/
	if ((cur_state == LEGUP_F_main_BB__71_27)) begin
		finish <= (memory_controller_waitrequest == 1'd0);
		if (start == 1'b0 && ^((memory_controller_waitrequest == 1'd0)) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to finish"); $finish; end
	end
end
always @(posedge clk) begin
	if ((cur_state == LEGUP_0)) begin
		return_val <= 0;
		if (start == 1'b0 && ^(0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to return_val"); $finish; end
	end
	/* main: %71*/
	/*   ret i32 %result.1.*/
	if ((cur_state == LEGUP_F_main_BB__71_27)) begin
		return_val <= main_59_result1_reg;
		if (start == 1'b0 && ^(main_59_result1_reg) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to return_val"); $finish; end
	end
end

endmodule 
module ram_dual_port
(
	clk,
	clken,
	address_a,
	address_b,
	wren_a,
	wren_b,
	data_a,
	data_b,
	byteena_a,
	byteena_b,
	q_a,
	q_b
);

parameter  width_a = 1'd0;
parameter  width_b = 1'd0;
parameter  widthad_a = 1'd0;
parameter  widthad_b = 1'd0;
parameter  numwords_a = 1'd0;
parameter  numwords_b = 1'd0;
parameter  init_file = "UNUSED.mif";
parameter  width_be_a = 1'd0;
parameter  width_be_b = 1'd0;
parameter  latency = 1;

input  clk;
input  clken;
input [(widthad_a-1):0] address_a;
input [(widthad_b-1):0] address_b;
output wire [(width_a-1):0] q_a;
output wire [(width_b-1):0] q_b;
reg [(width_a-1):0] q_a_wire;
reg [(width_b-1):0] q_b_wire;
input  wren_a;
input  wren_b;
input [(width_a-1):0] data_a;
input [(width_b-1):0] data_b;
// byte enable is unsupported by inferred RAMs
input [width_be_a-1:0] byteena_a;
input [width_be_b-1:0] byteena_b;

(* ramstyle = "no_rw_check", ram_init_file = init_file *) reg [width_a-1:0] ram[numwords_a-1:0];

/* synthesis translate_off */
integer i;
ALTERA_MF_MEMORY_INITIALIZATION mem ();
reg [8*256:1] ram_ver_file;
initial begin
	if (init_file == "UNUSED.mif")
    begin
		for (i = 0; i < numwords_a; i = i + 1)
			ram[i] = 0;
    end
	else
    begin
        // modelsim can't read .mif files directly. So use Altera function to
        // convert them to .ver files
        mem.convert_to_ver_file(init_file, width_a, ram_ver_file);
        $readmemh(ram_ver_file, ram);
    end
end
/* synthesis translate_on */

always @ (posedge clk)
if (clken)
begin // Port A
if (wren_a)
begin
    ram[address_a] <= data_a;
    q_a_wire <= {width_a{1'bX}};
end
else
    q_a_wire <= ram[address_a];
end
always @ (posedge clk)
if (clken)
begin // Port b
if (wren_b)
begin
    ram[address_b] <= data_b;
    q_b_wire <= {width_b{1'bX}};
end
else
    q_b_wire <= ram[address_b];
end



integer j;
reg [(width_a-1):0] q_a_reg[latency:1], q_b_reg[latency:1];

always @(*)
begin
   q_a_reg[1] <= q_a_wire;
   q_b_reg[1] <= q_b_wire;
end

always @(posedge clk)
if (clken)
begin
   for (j = 1; j < latency; j=j+1)
   begin
       q_a_reg[j+1] <= q_a_reg[j];
       q_b_reg[j+1] <= q_b_reg[j];
   end
end

assign q_a = (clken) ? q_a_reg[latency] : 0;
assign q_b = (clken) ? q_b_reg[latency] : 0;


endmodule
module rom_dual_port
(
	clk,
	clken,
	address_a,
	address_b,
	q_a,
	q_b
);

parameter  width_a = 1'd0;
parameter  width_b = 1'd0;
parameter  widthad_a = 1'd0;
parameter  widthad_b = 1'd0;
parameter  numwords_a = 1'd0;
parameter  numwords_b = 1'd0;
parameter  init_file = "UNUSED.mif";
parameter  latency = 1;

input  clk;
input  clken;
input [(widthad_a-1):0] address_a;
input [(widthad_b-1):0] address_b;
output wire [(width_a-1):0] q_a;
output wire [(width_b-1):0] q_b;
reg [(width_a-1):0] q_a_wire;
reg [(width_b-1):0] q_b_wire;

(* ramstyle = "no_rw_check", ram_init_file = init_file *) reg [width_a-1:0] ram[numwords_a-1:0];

/* synthesis translate_off */
integer i;
ALTERA_MF_MEMORY_INITIALIZATION mem ();
reg [8*256:1] ram_ver_file;
initial begin
	if (init_file == "UNUSED.mif")
    begin
		for (i = 0; i < numwords_a; i = i + 1)
			ram[i] = 0;
    end
	else
    begin
        // modelsim can't read .mif files directly. So use Altera function to
        // convert them to .ver files
        mem.convert_to_ver_file(init_file, width_a, ram_ver_file);
        $readmemh(ram_ver_file, ram);
    end
end
/* synthesis translate_on */

always @ (posedge clk)
if (clken)
begin
    q_a_wire <= ram[address_a];
    q_b_wire <= ram[address_b];
end



integer j;
reg [(width_a-1):0] q_a_reg[latency:1], q_b_reg[latency:1];

always @(*)
begin
   q_a_reg[1] <= q_a_wire;
   q_b_reg[1] <= q_b_wire;
end

always @(posedge clk)
if (clken)
begin
   for (j = 1; j < latency; j=j+1)
   begin
       q_a_reg[j+1] <= q_a_reg[j];
       q_b_reg[j+1] <= q_b_reg[j];
   end
end

assign q_a = (clken) ? q_a_reg[latency] : 0;
assign q_b = (clken) ? q_b_reg[latency] : 0;


endmodule
// Adding code from verilog file: ../../../boards/Virtex6/ML605/top.v


module ML605 (
       USER_CLOCK,
	    KEY,
	    SW,	    
       LED,
       LEDG,
		UART_RXD,
		UART_TXD

	    );

   input USER_CLOCK;
   input [4:0] KEY;
   input [7:0] SW;
   output [7:0] LED;
   output [7:0] LEDG;
   wire CLOCK_50;

    input UART_RXD;
    output UART_TXD;    
	wire clk = CLOCK_50;
	wire go = ~KEY[1];



   wire 	reset = ~KEY[0];
   wire 	start;
   wire [31:0] 	return_val;
   reg  [31:0] 	return_val_reg;
   wire 	finish;
   wire [3:0]	state;
   
   reg [6:0]   hex0, hex1, hex2, hex3, hex4, hex5, hex6, hex7;

   assign CLOCK_50 = USER_CLOCK;
   assign LED = 0;
   
	always @ (*) begin
		hex7 <= return_val_reg[31:28];
		hex6 <= return_val_reg[27:24];
		hex5 <= return_val_reg[23:20];
		hex4 <= return_val_reg[19:16];
		hex3 <= return_val_reg[15:12];
		hex2 <= return_val_reg[11:8];
		hex1 <= return_val_reg[7:4];
		hex0 <= return_val_reg[3:0];
	end
assign UART_TXD = 1'b0;

    parameter s_WAIT = 3'b001, s_START = 3'b010, s_EXE = 3'b011,
                s_DONE = 3'b100;

    // state registers
    reg [3:0] y_Q, Y_D;

    assign LEDG[3:0] = y_Q;

    // next state
    always @(*)
    begin
        case (y_Q)
            s_WAIT: if (go) Y_D = s_START; else Y_D = y_Q;

            s_START: Y_D = s_EXE;

            s_EXE: if (!finish) Y_D = s_EXE; else Y_D = s_DONE;

            s_DONE: Y_D = s_DONE;

            default: Y_D = 3'bxxx;
        endcase
    end

    // current state
    always @(posedge clk)
    begin
        if (reset) // synchronous clear
            y_Q <= s_WAIT;
        else
            y_Q <= Y_D;
    end

    always @(posedge clk)
        if (y_Q == s_EXE && finish)
            return_val_reg <= return_val;
        else if (y_Q == s_DONE)
            return_val_reg <= return_val_reg;
        else
            return_val_reg <= 0;


    assign start = (y_Q == s_START);

   
   top top_inst (
      .clk (clk),
      .reset (reset),
      .finish (finish),
      .return_val (return_val),
        .start (start)

    );

   

endmodule

// Adding code from verilog file: ../../../boards/StratixIV/DE4/top.v


module de4 ( 
    	     OSC_50_BANK2, 
             BUTTON, 
             LED, 
    	     SEG0_D, 
    	     SEG1_D 
	     ); 
   input OSC_50_BANK2; 
   input [1:0] BUTTON; 
   output [6:0] SEG0_D; 
   output [6:0] SEG1_D; 
   output [7:0] LED; 
   
   de2 de2_inst ( 
		  .CLOCK_50 (OSC_50_BANK2), 
		  .LEDG (LED), 
		  .KEY (BUTTON), 
		  .SW (), 
		  .HEX0 (SEG0_D), 
		  .HEX1 (SEG1_D), 
		  .HEX2 (), 
		  .HEX3 (), 
		  .HEX4 (), 
		  .HEX5 (), 
		  .HEX6 (), 
		  .HEX7 () 
		  ); 
   
endmodule
// Adding code from verilog file: ../../../boards/CycloneII/DE2/top.v


module de2 (
	    CLOCK_50,
	    KEY,
	    SW,
	    HEX0,
	    HEX1,
	    HEX2,
	    HEX3,
	    HEX4,
	    HEX5,
	    HEX6,
	    HEX7,
	    LEDG,
		UART_RXD,
		UART_TXD

	    );

   input CLOCK_50;
   input [3:0] KEY;
   input [17:0] SW;
   output [6:0] HEX0, HEX1,  HEX2,  HEX3,  HEX4,  HEX5,  HEX6,  HEX7;
   reg [6:0] 	hex0, hex1, hex2, hex3, hex4, hex5, hex6, hex7;
   

   output [7:0] LEDG;
    input UART_RXD;
    output UART_TXD;    
	wire clk = CLOCK_50;
	wire go = ~KEY[1];



   wire 	reset = ~KEY[0];
   wire 	start;
   wire [31:0] 	return_val;
   reg  [31:0] 	return_val_reg;
   wire 	finish;
   wire [3:0]	state;

   hex_digits h7( .x(hex7), .hex_LEDs(HEX7));
   hex_digits h6( .x(hex6), .hex_LEDs(HEX6));
   hex_digits h5( .x(hex5), .hex_LEDs(HEX5));
   hex_digits h4( .x(hex4), .hex_LEDs(HEX4));
   hex_digits h3( .x(hex3), .hex_LEDs(HEX3));
   hex_digits h2( .x(hex2), .hex_LEDs(HEX2));
   hex_digits h1( .x(hex1), .hex_LEDs(HEX1));
   hex_digits h0( .x(hex0), .hex_LEDs(HEX0));
   
	always @ (*) begin
		hex7 <= return_val_reg[31:28];
		hex6 <= return_val_reg[27:24];
		hex5 <= return_val_reg[23:20];
		hex4 <= return_val_reg[19:16];
		hex3 <= return_val_reg[15:12];
		hex2 <= return_val_reg[11:8];
		hex1 <= return_val_reg[7:4];
		hex0 <= return_val_reg[3:0];
	end
assign UART_TXD = 1'b0;

    parameter s_WAIT = 3'b001, s_START = 3'b010, s_EXE = 3'b011,
                s_DONE = 3'b100;

    // state registers
    reg [3:0] y_Q, Y_D;

    assign LEDG[3:0] = y_Q;

    // next state
    always @(*)
    begin
        case (y_Q)
            s_WAIT: if (go) Y_D = s_START; else Y_D = y_Q;

            s_START: Y_D = s_EXE;

            s_EXE: if (!finish) Y_D = s_EXE; else Y_D = s_DONE;

            s_DONE: Y_D = s_DONE;

            default: Y_D = 3'bxxx;
        endcase
    end

    // current state
    always @(posedge clk)
    begin
        if (reset) // synchronous clear
            y_Q <= s_WAIT;
        else
            y_Q <= Y_D;
    end

    always @(posedge clk)
        if (y_Q == s_EXE && finish)
            return_val_reg <= return_val;
        else if (y_Q == s_DONE)
            return_val_reg <= return_val_reg;
        else
            return_val_reg <= 0;


    assign start = (y_Q == s_START);

   
   top top_inst (
      .clk (clk),
      .reset (reset),
      .finish (finish),
      .return_val (return_val),
        .start (start)

    );

endmodule

module circuit_start_control (
    go,
    control_key
);
    input control_key;
    output go;
    assign go = control_key;
endmodule
module hex_digits(x, hex_LEDs);
    input [3:0] x;
    output [6:0] hex_LEDs;
    
    assign hex_LEDs[0] = (~x[3] & ~x[2] & ~x[1] & x[0]) |
                            (~x[3] & x[2] & ~x[1] & ~x[0]) |
                            (x[3] & x[2] & ~x[1] & x[0]) |
                            (x[3] & ~x[2] & x[1] & x[0]);
    assign hex_LEDs[1] = (~x[3] & x[2] & ~x[1] & x[0]) |
                            (x[3] & x[1] & x[0]) |
                            (x[3] & x[2] & ~x[0]) |
                            (x[2] & x[1] & ~x[0]);
    assign hex_LEDs[2] = (x[3] & x[2] & ~x[0]) |
                            (x[3] & x[2] & x[1]) |
                            (~x[3] & ~x[2] & x[1] & ~x[0]);
    assign hex_LEDs[3] = (~x[3] & ~x[2] & ~x[1] & x[0]) | 
                            (~x[3] & x[2] & ~x[1] & ~x[0]) | 
                            (x[2] & x[1] & x[0]) | 
                            (x[3] & ~x[2] & x[1] & ~x[0]);
    assign hex_LEDs[4] = (~x[3] & x[0]) |
                            (~x[3] & x[2] & ~x[1]) |
                            (~x[2] & ~x[1] & x[0]);
    assign hex_LEDs[5] = (~x[3] & ~x[2] & x[0]) | 
                            (~x[3] & ~x[2] & x[1]) | 
                            (~x[3] & x[1] & x[0]) | 
                            (x[3] & x[2] & ~x[1] & x[0]);
    assign hex_LEDs[6] = (~x[3] & ~x[2] & ~x[1]) | 
                            (x[3] & x[2] & ~x[1] & ~x[0]) | 
                            (~x[3] & x[2] & x[1] & x[0]);
    
endmodule
`timescale 1 ns / 1 ns
module main_tb
(
);

reg  clk;
reg  reset;
reg  start;
reg  waitrequest;
wire [31:0] return_val;
wire  finish;


top top_inst (
	.clk (clk),
	.reset (reset),
	.start (start),
	.waitrequest (waitrequest),
	.finish (finish),
	.return_val (return_val)
);


always @(posedge start)
	$display("Cycle: %d Function: main_tb Start", ($time-50)/20);
always@(posedge finish)
	$display("Cycle: %d Function: main_tb Finish", ($time-50)/20);
// Local Rams



initial 
    clk = 0;
always @(clk)
    clk <= #10 ~clk;

initial begin
//$monitor("At t=%t clk=%b %b %b %b %d", $time, clk, reset, start, finish, return_val);
@(negedge clk);
reset <= 1;
@(negedge clk);
reset <= 0;
start <= 1;
@(negedge clk);
start <= 0;
end

always@(finish) begin
    if (finish == 1) begin
        $display("At t=%t clk=%b finish=%b return_val=%d", $time, clk, finish, return_val);
        $display("Cycles: %d", ($time-50)/20);
        $finish;
    end
end

initial begin
waitrequest <= 1;
@(negedge clk);
@(negedge clk);
waitrequest <= 0;
end


endmodule 
